src/components/Modal/Modal.tsx
Pending confirmation that this is how we want to solve the procurement modal being larger than `lg`.
=> feat: Add ModalSize.xl.

src/forms/BoundToggleChipGroupField.tsx, src/forms/FormStateApp.tsx, src/forms/formStateDomain.ts, src/forms/index.ts, src/inputs/ToggleChipGroup.tsx, src/inputs/index.ts
Needed for future work in: https://app.clubhouse.io/homebound-team/story/2751/trade-partner-contacts
=> feat: add BoundToggleChipGroupField

package.json, src/components/internal/Option.tsx, src/components/internal/index.ts, src/inputs/MultiSelectField.stories.tsx, src/inputs/MultiSelectField.test.tsx, src/inputs/MultiSelectField.tsx, src/inputs/internal/ListBox.tsx, src/inputs/internal/SelectFieldBase.tsx, src/inputs/internal/SelectFieldInput.tsx, yarn.lock
Trying to simplify things on the way to fixing the "Empty means 'All'" behavior that is inherited from Filters that we don't want for regular MultiSelects.
=> chore: Inline ComboBox into SelectFieldBase.

src/components/GridTable.stories.tsx
Just to make it easier to compare/contrast default vs. condensed.
=> chore: Add story for default style.

src/components/Copy.tsx, src/components/index.ts, src/forms/FormStateApp.tsx, src/forms/StaticField.stories.tsx, src/forms/StaticField.tsx, src/forms/StaticLinkField.tsx, src/forms/index.ts
Upstreamed from procurement-frontend for occassionally adding static/FYI information to a form.
=> feat: Add StaticField, StaticLinkField from procurement.

src/components/ButtonMenu.stories.tsx, src/components/ButtonMenu.tsx
- https://app.clubhouse.io/homebound-team/story/6162/add-ability-for-buttonmenu-to-be-disabled
=> feat: Add ability for ButtonMenu to be disabled

src/index.ts, src/types.ts
Also add a default generic of `string` since that is typically what we use.
=> feat: Export HasIdAndName.

src/components/Filters/FilterModal.tsx, src/components/Filters/Filters.stories.tsx, src/components/Filters/testDomain.ts, src/components/Filters/types.ts, src/components/Filters/utils.tsx, src/inputs/Switch.tsx
Adds ability to support a Switch/toggle input in Filters.
Adds new labelStyle "filter" in Switch component that is applied when using Switch within FilterModal.
Includes example in Filters storybook
=> feat: Support Switch/toggle inputs in Filters

src/forms/FormLines.stories.tsx, src/forms/FormLines.tsx
Clubhouse: https://app.clubhouse.io/homebound-team/story/6395/add-ability-for-formlines-to-be-responsive
=> feat: Add ability for FormLines to be responsive

src/components/Filters/BooleanFilter.tsx, src/components/Filters/MultiFilter.stories.tsx, src/components/Filters/MultiFilter.tsx, src/components/Filters/SingleFilter.stories.tsx, src/components/Filters/SingleFilter.tsx, src/components/Filters/testDomain.ts
Probably going to add a story/test later before merging...
=> fix: Fix labels showing up in the modal.

src/components/BeamContext.tsx, src/components/SuperDrawer/ConfirmCloseModal.tsx, src/components/SuperDrawer/SuperDrawer.stories.tsx, src/components/SuperDrawer/useSuperDrawer.tsx, src/types.ts
Fix copy to match design.
Button layout should be stacked.
Update default button copy and allow for customized copy.
=> fix: Update SuperDrawer ConfirmCloseModal

src/components/Filters/DateFilter.tsx, src/components/Filters/testDomain.ts, src/components/internal/CompoundField.tsx, src/forms/BoundSelectAndTextField.stories.tsx, src/forms/BoundSelectAndTextField.test.tsx, src/forms/BoundSelectAndTextField.tsx, src/forms/index.ts, src/inputs/DateField.tsx, src/inputs/TextFieldBase.tsx
Utilizing CompoundField to create the BoundSelectAndTextField, expected for use on SchedulesV2 in Blueprint.
=> feat: Generic CompoundField component

src/components/internal/Option.tsx, src/components/internal/Popover.tsx, src/forms/BoundChipSelectField.test.tsx, src/forms/BoundChipSelectField.tsx, src/forms/index.ts, src/inputs/ChipSelectField.stories.tsx, src/inputs/ChipSelectField.test.tsx, src/inputs/ChipSelectField.tsx, src/inputs/index.ts, src/inputs/internal/ListBox.tsx
First pass a a ChipSelectField, utilizing our existing Listbox and Option components
=> feat: ChipSelectField

src/components/Modal/Modal.stories.tsx, src/components/Modal/TestModalContent.tsx, src/inputs/TextAreaField.tsx, src/inputs/TextFieldBase.tsx
Temporary fix to ensure measurement of the TextArea is properly done when rendered through portal in Modals.
=> fix: Fix issue when textarea measurement is incorrect when rendered through portal

src/Css.ts, src/inputs/SelectField.mock.test.tsx, src/inputs/SelectField.mock.tsx
[Shortcut Story](https://app.shortcut.com/homebound-team/story/10875/update-selectfieldmock-to-accept-disabledoptions)
=> feat: Update SelectFieldMock to accept disabledOptions

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx, src/components/Table/SortHeader.tsx, src/components/Table/columns.tsx, src/components/Table/styles.tsx, src/inputs/Checkbox.tsx, src/inputs/CheckboxBase.tsx
Creates new GridTable story for showing new header styles
=> feat: New Header styles for Beam tables

src/components/internal/DatePicker.tsx, src/forms/formStateDomain.ts, src/inputs/DateField.mock.test.tsx, src/inputs/DateField.stories.tsx, src/inputs/DateField.tsx
Updating `DatePicker` `disabledDays` prop to accept an array of Modifiers to fix TS error in this PR: https://github.com/homebound-team/internal-frontend/pull/1794/files#diff-b5da248aa7ad502a7ca5b33777e5a23e60a778ec6084a912bf80471f381480e1R61
=> feat: Update DatePicker disabledDays type to include Modifier[]

src/components/Table/GridTable.tsx, src/components/Table/columnSizes.ts
Starting to poke at refactoring the collapse state, to also support selected state, and wanted to do this clean up first.
=> chore: Extract columnSizes.

src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/RowState.ts
=> chore: Fix wonkiness in initial RowState PR.

src/hooks/useComputed.ts
This _should_ fix the behavior @Levi-Huynh was seeing on her local machine, of `useComputed` dropping re-renders.
My disclaimer is that I can't reproduce the bug locally, either on her branch, or in the `useComputed` test suite, but admittedly it seems intuitive that `setValue(tick)` is obviously wrong...
=> fix: Fix useComputed ticking incorrectly.

package.json, src/hooks/useComputed.ts
Include deep object comparison in useComputed
=> fix: useComputed to include deep object comparison

src/hooks/useComputed.test.tsx
Just given how brittle `useComputed` has been lately, wanted to backfill a test.
=> chore: Add test for useComputed deep equality.

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx, src/components/Table/sortRows.test.ts, src/components/Table/sortRows.ts, src/components/Table/useSortState.ts
Adds a 'caseSensitive' flag that can be added to change the default behavior.
=> feat: Client side Table sorting to be case insensitive by default

src/components/ToggleChips.stories.tsx, src/components/ToggleChips.tsx
Additionally fixes xss support and use CSS gap for spacing chips
=> fix: Support testids on ToggleChips. 

package.json, src/components/AutoSaveIndicator.stories.tsx, src/components/AutoSaveIndicator.test.tsx, src/components/AutoSaveIndicator.tsx, src/components/BeamContext.tsx, src/components/Icon.tsx, src/components/Modal/Modal.tsx, src/components/SuperDrawer/SuperDrawer.tsx, src/types.ts, yarn.lock
[SC-13020](https://app.shortcut.com/homebound-team/story/13020/dev-auto-save-notification-component)
Adds `<AutoSaveIndicator />` component
A bit more embellished than the comps: https://www.figma.com/file/aWUE4pPeUTgrYZ4vaTYZQU/%E2%9C%A8Beam-Design-System?node-id=12035%3A11589
=> feat: Sc 13020/dev auto save notification component

src/components/Table/GridTable.tsx
Just while reading the code for another ticket, no semantic changes.
=> chore: Extract filterRows method.

src/components/Table/GridTable.tsx
feat: [sc-17513] removing pin validation on the matches flag adding additional pin validation on the matchedChildren scenario, to always show pin tab but allow children filtering
=> feat: sc-17513: removing pin validation on the matches flag

src/index.ts
=> fix: Date Range added

src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx
=> feat: Add GridCellContent.css for cell-specific css.

src/components/ButtonMenu.stories.tsx, src/components/ButtonMenu.tsx, src/components/internal/Menu.stories.tsx, src/components/internal/MenuItem.tsx
=> feat: Add destructive styling to MenuItems

src/components/AutoSaveIndicator.tsx
Change to improve unit test on internal-frontend
=> chore: Add data-testid to AutoSaveIndicator

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/sortRows.ts
[SC-19459] - Adding the new Pin type with the filter boolean property to indicate the pin should be hidden while filtering in case it doesn't match the search term, adding stories and test for this scenario
=> feat: [SC-19459] Filterable Pins

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/GridTableApi.ts, src/components/Table/RowState.ts, src/components/Table/styles.tsx, src/forms/FormStateApp.tsx, src/forms/StepperFormApp.tsx
Feature request from [ticket](https://app.shortcut.com/homebound-team/story/19444/add-cell-highlighting-to-bulk-schedule-phases)
Add cell highlighting 
This branch is based off https://github.com/homebound-team/beam/pull/626
=> feat: SC-19444 cell highlighting

src/inputs/index.ts
Ops... forgot to add the import...
=> fix: add ToggleButton import

.storybook/beamTheme.tsx, .storybook/preview.tsx, beamLogo.tsx, src/components/Button.stories.mdx, yarn.lock
* Updated Storybook mdx files to use `Prop` component to display controls
* Added a Storybook theme to be able to update colors/fonts/typography
=> chore(storybook): Update storybook to use controls and update theme

src/components/Modal/Modal.tsx, src/components/Modal/TestModalContent.tsx, src/components/Snackbar/SnackbarNotice.tsx
Also ensures modal does not close when interacting with Snackbar
=> fix: Add role='alert' to Snackbar

src/components/Chip.tsx
Exposing the compact property from the Chip component to allow having chips used individually to have the xs font type
=> feat: sc-19881 | Compact Chip

src/components/AvatarButton.tsx, src/components/Button.tsx, src/components/ButtonMenu.stories.tsx, src/components/ButtonMenu.tsx, src/components/ButtonModal.stories.tsx, src/components/ButtonModal.tsx, src/components/IconButton.tsx, src/components/internal/OverlayTrigger.tsx, src/components/internal/Popover.tsx, src/interfaces.ts
Updates needed for this ticket [SC-22763](https://app.shortcut.com/homebound-team/story/22763/inline-editing-predecessors-successors)
=> feat: (SC-22763) Update button modal

src/components/ButtonModal.stories.tsx, src/components/Chip.stories.tsx, src/components/Chip.tsx, src/components/Tooltip.tsx
=> fix: position and z-index of a tooltip on a ButtonModal Component

src/components/Snackbar/SnackbarNotice.stories.tsx, src/components/Snackbar/SnackbarNotice.tsx
=> feat: SC-24180 - Update Snackbar Icon Colors

src/forms/BoundCheckboxField.test.tsx, src/forms/BoundCheckboxField.tsx, src/forms/BoundDateRangeField.test.tsx, src/forms/BoundDateRangeField.tsx, src/forms/BoundSwitchField.test.tsx, src/forms/BoundSwitchField.tsx
Also update BoundDateRange to be readonly based on field;
=> fix: [sc-26310] Mark Bound checkbox/switch disabled for readonly; 

.gitignore, .storybook/main.js, package.json, yarn.lock
[sc-25517]
See the description in https://github.com/homebound-team/internal-frontend/pull/3173 for a comprehensive explanation of this change.
=> build: enable turbosnap

src/inputs/TextAreaField.stories.tsx, src/inputs/TextField.stories.tsx, src/inputs/TextFieldBase.tsx, src/inputs/internal/SelectFieldBase.tsx
=> fix: remove maxWidth limit from textFieldBase

src/inputs/TextField.stories.tsx, src/inputs/TextFieldBase.tsx, src/inputs/internal/ListBox.tsx, src/inputs/internal/SelectFieldBase.tsx
=> fix: update styles for required/helper text and selectField dropdown

src/forms/BoundMultiLineSelectField.test.tsx, src/forms/BoundMultiLineSelectField.tsx, src/forms/index.ts, src/inputs/MultiLineSelectField.stories.tsx, src/inputs/MultiLineSelectField.test.tsx, src/inputs/MultiLineSelectField.tsx, src/inputs/index.ts
https://user-images.githubusercontent.com/24662091/210456406-06fe3f82-4bbb-493f-8d34-7369bedd1fa5.mov
=> feat: Add MultiLineSelectField

src/forms/FormLines.stories.tsx, src/inputs/TextFieldBase.tsx
=> fix: [SC-26383] Left label layout for read only fields

src/forms/FormLines.stories.tsx, src/forms/FormLines.tsx
=> feat: add labelStyle prop to FormLines

src/components/Layout/Layout.stories.tsx, src/components/Layout/ScrollableContent.tsx, src/components/Layout/ScrollableParent.tsx
Reverts homebound-team/beam#794
=> fix: Reverts "fix: ScrollableContent bgColor bug fix"

src/components/Filters/SingleFilter.test.tsx, src/components/Filters/SingleFilter.tsx, src/components/Filters/testDomain.ts
I want this `nothingSelectedText` to be able to work for multiple languages.
=> fix: nothingSelectedText for singleFilter

src/components/Layout/RightPaneLayout/RightPaneLayout.tsx
[SC-27545](https://app.shortcut.com/homebound-team/story/27545/task-super-drawer-not-closing-when-moving-across-projects-developments)
=> fix: (SC-27545) Close right pane on unmount page

src/components/Table/utils/TableState.ts
Discovered that there is an Apollo bug regarding applying TypePolicies when using a Promise.all. So instead, updating to make each async call in sequence.
=> fix: Async expand columns to be called in sequence

src/components/Pagination.stories.tsx, src/components/Pagination.test.tsx, src/components/Pagination.tsx
- Move pagination component from internal-frontend to Beam
=> feat: Add Pagination component

src/components/index.ts
- Debit of [SC-8167](https://app.shortcut.com/homebound-team/story/8167/beam-new-pagination-component)
- Add export `Pagination` component to `src/components/index.ts`
=> feat: Add Pagination export

src/components/Accordion.tsx, src/components/AccordionList.stories.tsx
* Adds an `omitPadding` prop to `Accordion` props so that you can remove padding from a child/nested accordion
=> feat: Add parent prop

src/components/Table/GridTableApi.ts, src/components/Table/utils/TableState.ts
With this we will re-render the expanded columns whenever the columns change
=> feat: re-render expanded columns when the columns change

src/components/ScrollShadows.stories.tsx, src/components/ScrollShadows.tsx
New component that adds shadows to a container to indicate it can be scrolled. It also hides the scrollbar.
Adds stories, but not tests as this is only presentational
=> feat: SC-33938: ScrollShadows component

src/components/internal/Menu.stories.tsx, src/components/internal/MenuItem.tsx
Reverts homebound-team/beam#869
=> fix: Revert "fix: resolve issue with ButtonMenu is close then open the menu and use cmd + click to open another tab"

src/components/Icon.stories.tsx, src/components/Icon.tsx
Also adds the "drag" icon to Storybook
=> feat: Add 'move' Icon

src/components/Icon.stories.tsx, src/components/Icon.tsx
[SC-35835](https://app.shortcut.com/homebound-team/story/35835/add-plan-details-page)
=> feat: (SC-35835) Add basement icon

src/components/Table/GridTable.test.tsx, src/components/Table/GridTableApi.ts, src/components/Table/components/CollapseToggle.test.tsx, src/components/Table/utils/CollapseState.ts, src/components/Table/utils/RowState.ts, src/components/Table/utils/RowStates.ts, src/components/Table/utils/RowStorage.ts, src/components/Table/utils/TableState.ts
Also created a `RowStorage` abstraction for reading/writing the collapsed ids to sessionStorage.
=> feat: Refactor collapse logic into RowState

src/components/Table/GridTable.tsx, src/components/Table/GridTableApi.ts, src/components/Table/components/EditColumnsButton.tsx, src/components/Table/components/ExpandableHeader.tsx, src/components/Table/components/Row.tsx, src/components/Table/types.ts, src/components/Table/utils/ColumnState.ts, src/components/Table/utils/ColumnStates.ts, src/components/Table/utils/ColumnStorage.ts, src/components/Table/utils/RowStorage.ts, src/components/Table/utils/TableState.ts, src/components/Table/utils/columns.tsx, src/components/Table/utils/utils.tsx
Similar to the same refactoring for RowState/RowStates, does the same for column state.
=> feat: Refactor column handling into ColumnState

src/components/AutoSaveIndicator.stories.tsx, src/components/AutoSaveIndicator.test.tsx, src/components/AutoSaveIndicator.tsx, src/components/Layout/PreventBrowserScroll.tsx
Plus:
**fix: AutoSaveIndictor to import from Beam**
=> fix: Add special webkit styling to fix overflow issues on ios Safari

src/components/Table/GridTable.test.tsx, src/components/Table/GridTableApi.ts, src/components/Table/utils/TableState.ts
=> fix: Fix missing RowState to GridDataRow map.

package.json, src/components/Table/GridTable.test.tsx, src/components/Table/GridTableApi.ts, yarn.lock
Even if the `data` elements are changing on each render.
=> fix: Make getSelectedRowIds stable.

src/inputs/TextFieldBase.tsx
Adds padding for multiline textfields to match the height of their single line counter parts
=> fix: Improve layout for multiline TextFields

README.md
Forcing a new published version
=> fix: Add NPM badge to README

src/components/Filters/TreeFilter.test.tsx, src/inputs/TreeSelectField/TreeSelectField.test.tsx, src/inputs/TreeSelectField/TreeSelectField.tsx, src/inputs/TreeSelectField/utils.ts, src/inputs/internal/ComboBoxInput.tsx
=> fix: TreeSelectField correct number of options selected

src/Css.ts, src/components/MaxLines.stories.tsx, src/components/MaxLines.tsx
MaxLines helps truncate long text vertically based on the number of lines the user wants to initially render. It provides a toggle to "Show More" / "Show Less".
The component listens for changes to its size & children to ensure it updates its need for truncation accordingly.
=> feat: MaxLines component

src/components/Tabs.stories.tsx, src/components/Tabs.tsx
=> feat: Support disabled tooltips on Tabs

src/components/internal/MenuItem.tsx
- Design wanted the divider to be darker (instead of lighter)
=> fix: update divider line color

src/hooks/useComputed.ts
Specifically on what fn vs. deps are.
=> docs: Expand useComputed docs.

package.json, src/components/Accordion.test.tsx, src/components/AccordionList.test.tsx, src/components/ButtonGroup.test.tsx, src/components/Chips.test.tsx, src/components/Snackbar/useSnackbar.test.tsx, src/components/Table/GridTable.test.tsx, src/components/Tabs.test.tsx, src/components/Tag.test.tsx, src/forms/StaticField.test.tsx, src/inputs/TextFieldBase.test.tsx, src/setupTests.tsx, yarn.lock
This method is built into Jest/jest-dom, instead of `toHaveStyleRule` which is `emotion/react`-specific method.
=> chore: Use toHaveStyle.

src/components/PresentationContext.tsx
=> feat: Add asterisk to required fields by default.

.cursor/rules/general.mdc, .cursor/rules/tests.mdc, src/components/Layout/FormPageLayout.tsx, src/components/RightSidebar.tsx
Updates to the `FormPageLayout` Component
* Updated strategy for the nav links intersection observer to better account for mixed section sizes.
* Adding polish to the right sidebar component to remove the layout shift and add transition animations 
* Misc design review padding/spacing updates
While working on this feature I also added in some initial `.cursor/rules` files to provide basic llm context for this repo
=> feat: [Hackday] [SC-68755] FormPageLayout design feedback & Cursor AI repo rules

src/components/Layout/FormPageLayout.tsx, src/components/RightSidebar.test.tsx, src/components/RightSidebar.tsx
[SC-70171](https://app.shortcut.com/homebound-team/story/70171/fe-cost-summary-sidebar-investigate-independent-scrolling)
LOOM VIDEO: https://www.loom.com/share/6004d1f2ba2a47fe9a8d988befaf84ac
=> feat: Add scroll and fixed icons to RightSideBar component

src/inputs/Switch.tsx
[SC-69302](https://app.shortcut.com/homebound-team/story/69302/beam-small-switch-update)
* Update `compact/small` switch width
=> fix: update switch widths

src/Css.ts, src/components/Button.stories.tsx, src/components/Button.tsx, truss-config.ts
[SC-69976](https://app.shortcut.com/homebound-team/story/69976/beam-update-buttons)
=> feat: Update button styles
