src/components/SuperDrawer/SuperDrawer.tsx, src/forms/FormStateApp.tsx, src/forms/SuperDrawerApp.stories.tsx
When using the canClose checks with the SuperDrawer, the drawer content would unmount when any checks failed. This causes implementation problems when using forms inside drawer content which would cause the form to lose it's state.
=> fix: Make SuperDrawer Content Stable when ConfirmationModal Appears

src/components/BeamContext.tsx, src/components/Modal/Modal.test.tsx, src/components/Modal/OpenModal.tsx, src/components/Modal/index.ts
An unintended artifact of moving the `ModalBody` / `ModalFooter` to using portals it that if tests render a `SomeModalComponent` directly, the content goes in the portals ... but the divs aren't mounted in the DOM yet, b/c that only happens when `openModal` is called.
So, this is just a wrapper to easily call `openModal` for tests ... would eventually be nice to not use this, and somehow have the divs already mounted.
Fwiw another approach would be to make another wrapper, like:
```
const r = await render(
<ModalComponent id=foo />,
withOpenModal,
withApollo(...)
);
```
Where `withOpenModal`'s `wrap` function would basically have a `useEffect` that calls `openModal`.
This seems a little more straight forward, but not sure, the `withOpenModal` is a little less code...
=> feat: Add OpenModal helper for testing modals.

src/inputs/DateField.stories.tsx, src/inputs/DateField.tsx
Making them behave width-wise like our other form fields:
(We didn't have this width convention figured out yet with date field was written.)
=> fix: Fix date field width, match others.

src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.tsx, src/components/Modal/TestModalContent.tsx
In procurement-frontend we have a modal that we know will always scroll,
so I want to keep the scroll bar always visible to avoid content jumping
left/right as the body gets wider/narrower.
=> feat: Add Modal.forceScrolling to always scroll.

src/inputs/TextAreaField.stories.tsx, src/inputs/TextFieldBase.tsx
When looking at a screen that has both regular `TextField`s as well as `TextAreaField`s it looked weird that the `TextAreaField`'s content was indented more than the regular text fields.
=> fix: Update TextAreaField padding to match TextField.

src/components/Filters/utils.tsx, src/inputs/MultiSelectField.test.tsx, src/inputs/SelectField.test.tsx, src/inputs/internal/SelectFieldBase.tsx
The "All" behavior was hard-coded for filters and not something we want for like editing in a form.
=> feat: Add nothingSelectedText to customize All behavior.

src/components/BeamContext.tsx, src/components/Modal/Modal.tsx, src/components/Modal/useModal.tsx, src/components/SuperDrawer/SuperDrawer.tsx, src/components/SuperDrawer/SuperDrawerContent.tsx, src/components/SuperDrawer/useSuperDrawer.test.tsx, src/components/SuperDrawer/useSuperDrawer.tsx, src/types.ts
I'm playing with open/closing the drawer based on routes, i.e. `/requests/preq:1` would auto-open the drawer to `preq:1`.
It's basically working, but I need a way to know "the drawer is closed" to change the history from `/requests/preq:1` back to just `/requests`.
Ironically, this is re-using `onClose` that was originally added for the "can I close" confirmation that we re-purposed into `addOnCloseCheck` or what not, but as a "close has actually happened".
=> feat: Call OpenInDrawerOpts.onClose after close has happened.

src/forms/BoundSwitchField.tsx, src/forms/BoundSwitchFieldTest.tsx, src/forms/FormLines.stories.tsx, src/forms/FormLines.tsx, src/forms/FormStateApp.tsx, src/forms/index.ts, src/inputs/Switch.tsx, src/inputs/index.ts
For Trade Partner Contact screens in internal-internal.
FormLines is kinda WIP, but figure it might as well be WIP here instead of copy/pasting it across internal-frontend and procurement-frontend.
=> feat: Add BoundSwitchField, FormLines.

src/components/SuperDrawer/SuperDrawer.tsx
After checks have passed, the useSuperDrawer hook will call the onClose callback.
=> fix: Remove SuperDrawer from calling onClose

.storybook/main.js, package.json, src/components/Label.tsx, src/components/Modal/Modal.stories.tsx, src/forms/BoundDateField.tsx, src/forms/BoundMultiSelectField.tsx, src/forms/BoundNumberField.tsx, src/forms/BoundSelectField.tsx, src/forms/BoundTextField.tsx, src/forms/FormContext.ts, src/forms/FormLines.stories.tsx, src/forms/FormLines.tsx, src/forms/FormStateApp.tsx, src/forms/formStateDomain.ts, src/forms/labelUtils.ts, src/index.ts, src/inputs/DateField.tsx, src/inputs/NumberField.tsx, src/inputs/TextField.stories.tsx, src/inputs/TextField.test.tsx, src/inputs/TextField.tsx, src/inputs/TextFieldBase.tsx, src/inputs/internal/SelectFieldBase.tsx, src/inputs/internal/SelectFieldInput.tsx, src/interfaces.ts, yarn.lock
Building out a form for Trade Partner Contacts and infra-izing various things about forms.
The biggest change is that most `...Field`s learned a new `required` prop, that if set to `true` or `false`, they'll add `Required` / `Optional` to their label (the text "Required" or "Optional" is currently controlled by a new `FormContext`).
Also the `Bound...Field`s learned to pass `field.required` in as the new `required` prop, so for the most part everything should wire together automatically/for free, based on `rules: [required]` in the form config.
=> feat: Form lines, widths, required labels

src/components/GridTable.test.tsx, src/components/GridTable.tsx
Previously we had just `value` which was used for both filtering + sorting.
But you may want filtering to use text like "Accepted" and "Rejected" but, for whatever reason, have "Rejected" sort before "Accepted" so have sort values of like 2 and 1 respectively.
=> feat: Add dedicated cell sortValue.

src/components/GridTable.stories.tsx, src/components/GridTable.test.tsx, src/components/GridTable.tsx
Two changes:
* I went to use the new `sortValue` and realized it didn't work if there was not always a `value` key (bad `keyof` check)
* If client-side sorting, seems like a good default is to just sort by 1st column asc, it's come up before that our tables "don't look like they support sorting", when really it's just b/c they aren't initially sorted and the user has to click to see "oh I can sort"
=> fix: Always initial sort, fix sortValue w/o value.

src/components/Button.stories.tsx, src/components/Button.tsx, src/components/ButtonGroup.tsx, src/components/IconButton.stories.tsx, src/components/IconButton.tsx, src/components/Tooltip.stories.tsx, src/components/Tooltip.tsx, src/interfaces.ts
This is a) a blatant copy/paste from one of @DeanGilewicz 's WIP PRs + b) a long-standing need to be able to `s/BP Button/Beam Button` in BP, because we have quite a few places that use current BP Button's `disabledReason` prop.
=> feat: Add Button.disabled can be a tooltip

src/components/GridTable.tsx
Lauren wants to try making all table have sticky headers by default, but we frequently have issues with stickiness (...I think usually related to trying to also sticky other non-table content above the table itself).
So this PR doesn't actually change the default, it just exposes a `setGridTableDefautls` so that we can push out a preview URL in BP with the change, and see how it goes.
=> feat: Allow setting default sticky headers.

package.json, yarn.lock
When upgrading typescript, I'd upgraded typescript-transform-paths for good measure, but turns out it causes this bug:
https://github.com/LeDDGroup/typescript-transform-paths/issues/132
=> fix: Bump down typescript-transform-paths to avoid require bug.

src/components/Filters/Filters.stories.tsx, src/components/Filters/utils.tsx, src/utils/defaultLabel.test.ts, src/utils/defaultLabel.ts
I.e. a filter definition of `{ marketId: ... }` will use "Market" as the default label.
=> feat: Use the filter def key as a default label.

src/components/Tabs.test.tsx, src/components/Tabs.tsx
Instead of `tid[i]` (which outputs `tabs_1` / `tabs_2`) for each tab's button, we use `tab[value]` which (outputs `tabs_${value}`).
The `tabs_1` confuses rtl-utils's `r.foo` lookup because it interprets `_1` suffixes as "looking for multiple things.
=> fix: Make Tabs test ids more rtl-utils friendly.

src/inputs/SelectField.test.tsx, src/inputs/TextAreaField.stories.tsx, src/inputs/TextAreaField.test.tsx, src/inputs/TextAreaField.tsx, src/inputs/TextField.stories.tsx, src/inputs/TextField.test.tsx, src/inputs/TextField.tsx, src/inputs/TextFieldBase.tsx, src/inputs/internal/SelectFieldInput.tsx
To support flipping between read/edit on forms that use `BoundTextField` / `BoundTextAreaField`.
=> fix: Render TextFields as just text when readOnly.

src/components/GridTable.test.tsx, src/components/GridTable.tsx
I.e. if a GraphQL query has not come back yet, we still want to show the header.
=> feat: Allow passing undefined to simple row factories.

src/inputs/TextField.test.tsx, src/inputs/TextFieldBase.tsx
Previously we were able to check for the 'readonly' attribute added to the `<input />` element. Now that the read only version is not an input element, we are adding an explicit data-readonly attribute to help identify that the TextField is in the expected state
=> fix: Add 'data-readonly' attribute to help with testing.

src/components/Tabs.stories.tsx, src/components/Tabs.test.tsx, src/components/Tabs.tsx
This matches a change @bdow made to the old BP tabs, requested by Lauren. It should also help some of our create flows that "open in drawer, only enable the details tab" hopefully for-free match the mocks, where the "in drawer" create flows leave out the tabs.
Granted, sometimes the different between create-flow vs. update-flow is more than just "don't show the other tabs", but hopefully this is a good default.
=> feat: Hide tabs if only one is active.

src/Css.ts, src/components/Stepper.tsx, truss/index.ts
Reset Stepper's button styles to allow for wrapping.
=> fix: Do not allow button text to wrap

src/components/Button.stories.tsx, src/components/Button.tsx, src/components/IconButton.stories.tsx, src/components/IconButton.tsx, src/components/Tooltip.tsx, src/interfaces.ts
Allow Beam buttons to render as links, both absolute and relative (using react-router).
Allow Beam buttons to render tooltips for non-disabled buttons
=> feat: CH-6240: Update Beam Button to have feature parity with BP buttons.

package.json, src/index.ts, yarn.lock
Bumping rtl-utils back to 2.46.0.
Remove exporting of Beam's RTL and Storybook helpers, which have a direct dependency on @homebound/rtl-utils. This was causing rtl-util to be bundled with our production builds in frontend applications.
=> fix: Remove dependency of rtl-util from build

src/forms/FormLines.tsx
Going to hold off on this, b/c maybe this ends up being configurable, i.e. compact fields have 16px padding and non-compact fields have 24px padding.
Also it might be that all of Blueprint forms are defacto compact.
=> fix: Reduce form line margin per #beam discussion.

README.md, src/components/Modal/useModal.tsx, src/components/Tooltip.tsx, src/forms/BoundToggleChipGroupField.tsx
Added a fixed strategy so the tooltip component will always sit on top of anything.
=> fix: Add Create Portal to Tooltip component

src/inputs/MultiSelectField.test.tsx, src/inputs/internal/SelectFieldBase.tsx, src/inputs/internal/SelectFieldInput.tsx
Usability issue discovered in user testing - When a user is actively using the MultiSelectField and chooses a single option, that option's text is used to populate the input. However, user expectations were for that input value to be removed and allow them to start typing to filter again without having to delete the current input.
Fix is to empty out the input value upon selection change for MultiSelectFields. If only one option is selected, then upon blurring the field the selected option should show in the input.
=> fix: MultiSelectField to empty input value upon selecting an option

package.json, src/components/Table/CollapseToggle.tsx, src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx
We hadn't gotten around to sorting nested rows.
To sort nested rows, we need to know the original non-flatted structure.
I originally thought we could/should decipher this by going through the flattened list and observing the `kind` values. I.e. if we saw `kind=parent, kind=child, kind=child, kind=grandchild, kind=parent` we could probably guess the tree.
That said, it's a lot simpler to just be passed the tree as-is, because currently all of the code that passes nested rows is `flatMap`-ing from a nested structure anyway.
So, we make a large breaking change by removing the `parentIds` key that used to hint at the structure of parent/children, and instead just add a `GridDataRow.children` to make `rows` now a recursive/non-flat structure.
We still flatten before handing off to the css …
=> feat: Sort nested rows.

src/components/Filters/Filters.stories.tsx, src/components/Filters/SingleSelectFilter.test.tsx, src/components/Filters/SingleSelectFilter.tsx, src/components/Filters/testDomain.ts, src/hooks/usePersistedFilter.test.tsx
This matches multi select / boolean filter / etc. behavior, and means users don't have to add their own "All" options that can act slightly weird due to the "empty vs. All vs. actual value" tri-state.
=> feat: Add 'All' to single select filters.

src/inputs/SelectField.mock.tsx
Passing the disabled prop into the select element to allow testing that a `SelectField` is disabled.
=> fix: pass disabled prop to select element

package.json, src/components/Table/GridTable.tsx, yarn.lock
Something about TypeScript 4.4 made the type inference for `simpleRows` wonky, and this fixes it... :shrug:
=> fix: Better simpleRows type.

src/forms/FormHeading.stories.tsx, src/forms/FormHeading.tsx, src/forms/FormLines.tsx
Our `FormHeadings` are consistently `baseEm`, which is almost so tiny to just `Css...` it's not worth component-izing. But, I dunno, I like it...
I'm also trying out a `cloneElement`-based approach for doing "only `mt4` the 2nd FormHeading".
Maybe should use `not nth-type-of` selectors or something, but I think that would require a hard-coded CSS class name for the selector to add margin only to `FormHeading`s and not other children.
I've been wanting to at least get this `cloneElement` approach working for awhile now, so admittedly ~80% of my motivation for this PR was using it as a good test case for `cloneElement` hacking. :-)
=> feat: Add FormHeading proof-of-concept.

src/components/internal/Popover.tsx
Try it out with the Filters component: 
https://60466f7d43c37c0021788867-jgwefxrlvi.chromatic.com/?path=/story/components-filters--filter
=> fix: Allow propagation of onPointerDown event through Popover when open

.storybook/.babelrc, package.json, src/Css.ts, src/components/SuperDrawer/SuperDrawer.stories.tsx, src/components/Table/GridRowLookup.ts, src/components/Table/GridTable.nestedCards.test.tsx, src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/index.ts, src/components/Table/nestedCards.test.tsx, src/components/Table/nestedCards.tsx, src/components/Table/simpleHelpers.ts, src/components/index.ts, truss/index.ts, truss/package-lock.json, truss/package.json, yarn.lock
Screenshot from the story (the story only has a single `name` column):
Here with a `gap1` turned on to show the DOM structure:
So the DOM is still flat, and we alternate "content rows" and "chrome rows" (that have the open/close rounded borders + spacers).
And note that even though this chrome row is a single div to css grid/react-virtuoso:
It is 1 outer div + three inner divs: close the previous row, add a spacer between cards, open the new row.
Also for the content rows:
The 1st and last cells (in this case it's the same cell b/c there is only 1 column) have N-levels of pad-left/pad-right added around their normal `GridColumn`-generated output, which achieves the nudging-in look.
Other than that, everything is still stock gridtable.
=> feat: Nested cards

src/components/Filters/Filters.stories.tsx, src/components/Filters/ToggleFilter.test.tsx, src/components/Filters/ToggleFilter.tsx
We don't need it immediately, but just following up the trend from @Chieze-Franklin 's PR, it seems like `toggleFilter` would really use any values for "on" / "off" instead of just booleans.
=> feat: Generalize toggleFilter for non-boolean on/off values.

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/nestedCards.test.tsx, src/components/Table/nestedCards.tsx, src/components/Table/sortRows.ts
I.e. the "add task" use case.
Note that "Add" is getting pulled to the top, even though it's the "last child" when passed in, by the client-side sorting (because "Add" comes from "child g1c1").
So we'll either need to implement the "don't sort levels one or two" logic, or IMO what I'd prefer is something more like tagging rows as special i.e. `{ kind: "add", pin: "first" | "last" }` where the client-side sorting would recognize rows with the `pin` key set and automatically shove them first/last as appropriate, either before/after the otherwise normally sorted children. 
---
Update: I was looking for a distraction from the chores I'm supposed to be doing, so went ahead and added `GridDataRow.pin` so now Add will stay last.
=> feat: Allow non-card kinds in nested cards.

src/components/Layout/Layout.stories.tsx, src/components/Tabs.stories.tsx, src/components/Tabs.test.tsx, src/components/Tabs.tsx, src/components/testData.tsx
Allows Tabs to accept a 'path' property which will render the Tab component as a link, using React Router to navigate between tabs.
Selected tab will be based on the route instead of passing a "selected" property into the Tabs component.
Change default Tab element to be a Button which will allow for native 'on Enter key' handling in DOM. In order to achieve this we also need to properly set focus on the element as the user navigates between them via Keyboard.
=> feat: Tabs support routes

src/components/internal/Option.tsx, src/inputs/internal/ListBox.tsx, src/inputs/internal/SelectFieldBase.tsx
A bug was originally discovered when triggering the ListBox on top of the SelectField where an option would be immediately selected due to selection happening onPointerUp and the ListBox being triggered onPointerDown. This was originally fixed by setting 'shouldSelectOnPressUp: false' for the Options within the ListBox. Though, this traded one bug for another. Recently discovered was that the subsequent onPointerDown event fired after selecting an Option could have adverse effects, such as trigger a modal to close if the ListBox was rendered on top of the Modal's underlay element.
To address this issue, we went back to the root problem and now prevent the Menu from ever rendering above its trigger element. This is done by utilizing the OverlayPosition props, which include a 'maxHeight' …
=> fix: Do not allow ListBox to show on top of trigger element

src/components/Modal/Modal.stories.tsx, src/components/Modal/OpenModal.tsx
I went through much gnashing of teeth to very specifically pad form elements in a modal, particularly b/c all of the tape / measure / etc. extensions I found (for both chrome and FF), and also FF's built-in measure feature, all would cause the modal to close.
This adds a `keepOpen` prop to `OpenModal` that skips the `openModal`/`closeModal` hook and just redirectly renders the `Modal` in the DOM.
I'm planning on making this the default for any story that uses `modal: true` in blueprint, b/c I figure testing close is not really that important in stories.
=> fix: Add OpenModal.keepOpen for doing tape-style measurements.

src/components/Layout/FullBleed.tsx, src/components/Layout/Layout.stories.tsx, src/components/Layout/ScrollableParent.tsx
As I started to pull `<ScrollableParent />` and `<ScrollContent />` components into Blueprint, I found it quite cumbersome to define the consistent padding between all the pages. This change allows for setting that consistent padding, but also provides a `<FullBleed />` component that utilizes the set padding to have the component expand the full width of the `<ScrollableParent />`
=> fix: Support setting padding as part of nested scrolling layout

src/components/Tooltip.tsx
- define a z-index for tooltip to ensure it is displayed on top of other overlays
=> fix: Tooltip positioning issue when used inside of SuperDrawerContent

src/components/NavLink.tsx
The width isn't really necessary. Having a hard coded with is more trouble than its worth, and the size should be flexible based on content and parent element.
=> fix: Remove hardcoded width from NavLink side variant

src/inputs/CheckboxBase.tsx
Removing the `topPx(2)` definition from the Checkbox as that misaligns the checkbox with other content if not given a label. Instead adding a "margin-top: -2px" to the label to achieve the same alignment result
=> fix: Update Checkbox alignment styles

src/components/Layout/ScrollableParent.tsx, src/components/Tabs.tsx
Margin between tabs and tab content should be 24px.
Adding in `overflow: overlay` even though it is only supported in Webkit browsers, though that is the majority of our users. Keeping `overflow: auto` defined as a fallback for any browser that does not support overflow: overlay. 'overlay' will prevent the scrollbars from pushing content in when are needed, which pushes the content inwards.
=> fix: Update spacing and scrolling styles after QA with design

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx
Allows implementer to define a default empty cell value for the whole table. For instance, in many tables in Blueprint we want to show the "-" character if there is no data for that cell
=> feat: Support 'emptyCell' GridStyle.

src/components/Tabs.stories.tsx, src/components/Tabs.tsx
In order to migrate Blueprint's existing tabs to Beam, then we need to support more than just a Icon as the decoration on the tab.
=> feat: Support endAdornment in Tab for decorations other than icons

src/components/Tabs.test.tsx, src/components/Tabs.tsx
This is to support an existing requirement in Blueprint where Stage Tabs may be hiding the Planning stage, and the Construction stage may be disabled, making PreCon the only active stage. In this case, as part of Product requirements (which may be outdated) we want to show both the Pre-Con and disabled Construction tabs. Regardless if the requirements are outdated, I think allowing showing the single enabled tab is useful.
=> fix: Allow forcing tabs to show even if only one is enabled

package.json, yarn.lock
I was originally thinking it'd be cute to have it be optional, b/c I think only certain row-hover codepaths in GridTable use it, but meh, it's simpler to just always require it (I'm pruning unused-looking-ish dependencies from internal-frontend).
=> fix: Add tinycolor as a direct dependency.

src/components/Tabs.stories.tsx, src/components/Tabs.tsx
Tab panel element is always rendered, which eliminates the possibility of TabContent benefiting from collapsable margins. This resulted in the margin-top: 24px being applied under an empty Tab Panel element, and causing extra white space. With this change if the tabs are hidden, then the TabContent will not apply a margin-top definition.
_Caveat_: If the user supplies TabActions and the Tabs are hidden, then we will not have space between the Tab Actions and the Tab Content. This is probably fine for the most part as the Actions are right aligned, and the content will more than likely be left aligned. If it becomes an issue the user can always conditionally apply their own defined margin for the TabContent via `contentXss`, or set `alwaysShowAllTabs` to true, and that'd take care of the …
=> fix: Avoid unnecessary whitespace

src/components/Button.stories.tsx, src/components/Button.tsx, src/components/Filters/MultiFilter.stories.tsx, src/components/Filters/SingleFilter.stories.tsx
The text variant will not supply any padding and is made to look like regular text. It uses the same default button styling for font-size, weight, etc.
=> feat: 'text' variant for Button

src/components/Modal/Modal.stories.tsx, src/components/Modal/TestModalContent.tsx, src/inputs/internal/DatePickerOverlay.tsx
Previously, I thought FocusScope was required to allow the DateField to properly work within a Modal, which is why it was added. Turns out it is not an issue. Removing this FocusScope allows for the focus now to stay within the DateField's input.
=> fix: Remove FocusScope on DatePickerOverlay

src/components/IconButton.stories.tsx, src/components/Modal/Modal.tsx, src/components/Modal/TestModalContent.tsx, src/inputs/RichTextField.tsx
Removing the document.getElementById call to grab the editor element and replacing with a useRef. This wasn't safe as when using the RichTextField within a Portal (such as a Modal) it was possible that the element for the editor is not yet in the DOM.
Now listening to the 'trix-initialize' event in order to set the editor ref and call 'loadHTML'. This is not immediately available off of the element's ref because the 'editor' is attached to the 'trix-editor' web component using 'requestAnimationFrame', which waits for the event loop to clear before running its execution (similar to a setTimeout(..., 0))
=> fix: RichTextField to initialize based on trix supplied init event

src/components/ButtonMenu.stories.tsx, src/components/ButtonMenu.tsx, src/components/Tooltip.tsx
The previous implementation to clone the element resulted in loss of functionality for the cloned element as the tooltip trigger props would overwrite pointer events tied to the element.
Now wrapping in our own span to provide the tooltip actions and keeps the existing children component/element as is.
=> fix: Remove cloneElement from Tooltip to avoid

src/inputs/NumberField.test.tsx, src/inputs/NumberField.tsx
Additional change: 'days' type does not allow for decimal values - integers only.
=> fix: NumberField to support displaying plus sign for positive numbers.

src/inputs/ChipTextField.stories.tsx, src/inputs/ChipTextField.test.tsx, src/inputs/ChipTextField.tsx
ChipTextField is expected to be used in SchedulesV2 when creating a new Subcategory. It is mostly a self contained form, which is why we handle an onEnter (for "Save") and listening to the "Escape" key to blur the field.
=> feat: ChipTextField

src/components/Chip.test.tsx, src/components/Chip.tsx, src/components/ToggleChip.tsx, src/inputs/ChipSelectField.stories.tsx, src/inputs/ChipSelectField.test.tsx, src/inputs/ChipSelectField.tsx
If the text within a Chip exceeds the width allotted to it, then it will use an ellipsis. A title attribute is also tied to the Chip to display the full value of the chip on hover.
=> fix: All Chip components to only be one line of text

src/components/Chip.tsx, src/components/Tag.tsx, src/components/ToggleChip.tsx, src/inputs/ChipSelectField.tsx
The result reveals more of the content of the Chip's/Tag's text, utilizing all of the space of the available to the Chip/Tag.
=> fix: Break mid word in Chips and Tags when truncated

src/inputs/ChipSelectField.test.tsx, src/inputs/ChipSelectField.tsx, src/inputs/DateField.test.tsx, src/inputs/DateField.tsx, src/inputs/NumberField.test.tsx, src/inputs/NumberField.tsx, src/inputs/SelectField.test.tsx, src/inputs/TextAreaField.test.tsx, src/inputs/TextAreaField.tsx, src/inputs/TextField.test.tsx, src/inputs/TextField.tsx, src/inputs/internal/SelectFieldBase.tsx
SelectField, ChipSelectField, and DateField should blur whenever a user changes the value.
TextField, TextAreaField (with preventNewLines), NumberField, and DateField should blur when the user hits the Enter key
=> feat: Fields should blur on interactions

src/forms/BoundChipSelectField.test.tsx, src/inputs/ChipSelectField.test.tsx, src/inputs/ChipSelectField.tsx, src/inputs/internal/ListBox.tsx, src/inputs/internal/ListBoxSection.tsx, src/inputs/internal/Option.tsx, src/inputs/internal/SelectFieldBase.tsx, src/inputs/internal/VirtualizedOptions.tsx, src/inputs/internal/constants.ts
ListBox now supports two sections, (1) Options, and (2) Persistent Actions. The Options section will scroll independently of the Persistent Actions, make the Actions always visible.
Sections will only be rendered if necessary, otherwise it will just be a flat list of options as it works today. If the onCreateNew prop is passed to ChipSelectField, then we'll create the two sections. Right now there are a lot of assumptions in the code that we'll only ever have at most two sections, and that the second section is the Persistent Actions, and there will only ever be a single persistent action. Prototype, period. :)
Bugs fixed:
- Auto scroll to focused item ONLY if using virutal focus (i.e. in SelectField where we use a Combobox and the browser focus stays within the input field). This fixes …
=> fix: ChipSelectField and ListBox updates

src/components/Table/GridTable.stories.tsx, src/components/Table/nestedCards.test.tsx, src/components/Table/nestedCards.tsx
TLDR - GridTable is performing expensive JSX computations in 2 places which it shouldn't be (at-least/especially for virtualized lists):
1. vistRows
2. sortRows - NOTE: Not addressing this, since we aren't using sorting at the moment
Here is a Profile from main for a virtualized list with 1500 rows (2.1 seconds to visitRows):
Here is that same virtualized list on this branch (24 milliseconds to visitRows):
~~NOTE: Still working on getting the styling to be correct with this approach.~~ All good now 👍  🍣
=> perf: no JSX in visitRows => 100x improvement

.storybook/main.js, .storybook/preview.tsx, package.json, src/components/Icon.tsx, src/components/Label.tsx, src/inputs/ChipSelectField.stories.tsx, src/inputs/ChipSelectField.tsx, src/inputs/internal/ListBox.tsx, src/inputs/internal/ListBoxChip.tsx, src/inputs/internal/ListBoxToggleChip.tsx, src/utils/options.ts, yarn.lock
Only run the 'listData.update' within useEffect after first render
Memoize 'selectChildren' to only re-evaluate if the options/items change.
Separate "CreateNewField" to isolate its state management.
Separate ListBoxChip component.
getOptionValue/Label default values are stored as constants. These were changing identity unnecessarily.
Profiling against Schedules V2 on Blueprint:
Created a Perf Test story for ChipSelectField that will be ignored by Chromatic snapshots. It is a single ChipSelectField with 100 options. See the below screenshots for change in performances recorded in the  Performance Storybook Addon. (Set at 1 copy and 100 samples)
=> fix: Performance improvements for ChipSelectField

src/components/Table/GridTable.tsx, src/components/Table/SchedulesV2.stories.tsx
This PR adds an additional GridTable prop to provide virtual tables with a footer. 
This uses the [Footer component](https://virtuoso.dev/footer/) from virtuoso.
=> feat: Add optional footer padding for virtual tables; add optional scrolling for tables

src/components/Tooltip.test.tsx, src/components/Tooltip.tsx, src/inputs/MultiSelectField.mock.tsx, src/inputs/SelectField.mock.tsx, src/inputs/SelectField.stories.tsx, src/inputs/TextFieldBase.tsx, src/inputs/internal/SelectFieldBase.tsx, src/inputs/internal/SelectFieldInput.tsx
SelectField to support tooltip text as part of the `readOnly` prop, similar to `disabled`.
=> feat: Support Tooltip on readOnly TextFieldBase

src/inputs/MultiSelectField.stories.tsx, src/inputs/SelectField.stories.tsx, src/inputs/internal/SelectFieldBase.tsx
Expose the `placeholder` props which already works in the background via prop spread but it was being lost when used with `BoundSelectFields`.
=> feat: Expose SelectField and MultiSelectField `placeholder` prop

src/components/Table/CollapseToggle.test.tsx, src/components/Table/CollapseToggle.tsx, src/components/Table/GridTable.tsx
I accidentally broke the collapse chevron behaviour with my perf fix the other day.
Before:
https://share.getcloudapp.com/DOumRXBZ
After:
https://share.getcloudapp.com/E0uoG2lq
=> fix: Update for the collapse icon to correctly reflect the state of the row

src/components/Table/GridTable.tsx
On 2.95.1 - 165ms render of all table rows
With this fix - 70ms render of only the changed row
=> perf: Fix regression caused by style change

src/inputs/SelectField.mock.test.tsx, src/inputs/SelectField.mock.tsx
- update disabledOptions logic since no need to `toString()` which was failing when `getOptionValue(option)` was `undefined`
- update test to confirm forked case
=> fix: update disabledOptions logic

src/forms/BoundTextField.test.tsx, src/forms/BoundTextField.tsx, src/inputs/TextField.test.tsx, src/inputs/TextField.tsx
We recently introduced that hitting the "Enter" on a TextField would immediately blur the field. Because we blur out of the field, then we no longer trigger default form submission behavior when a user hits the "Enter" key when the `<input />` element is wrapped in a `<form />`. It is unfortunate to have this be the default behavior in my opinion, but perhaps we can change this in the future? For now, providing an `onEnter` as another way to support submitting a form via the Enter key when within a TextField.
=> fix: Expose an onEnter callback for TextField

src/forms/BoundNumberField.test.tsx
I was seeing `$0.00` show up where I didn't want it, and thought it was maybe from `BoundNumberField` turning `null --> 0`, but turns out it was a bug in my code (gasp). Pushing up the test for good measure.
=> chore: Add test showing BoundNumberField is fine with null.

package.json, src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx
Use `minWidth: fit-content` on the virtual table's wrapping element. This allows for the table to dictate its size based on the width of the GridRows, and ensures the chrome rows always adjust to the GridRows size.
=> fix: Ensure chrome rows always fit to GridRows

src/components/internal/CompoundField.tsx
Fixes an issue where `onFocus` and `onBlur` are getting overwritten (a problem for `Bound` type fields that never expect `onFocus` or `onBlur` to be passed in externally, but due to using `...others` prop spread below, the existing logic gets clobbered).
=> fix: Use CSS only solution to style focus state for CompoundField

src/components/Table/GridTable.tsx, src/components/Table/SchedulesV2.stories.tsx, src/components/Table/nestedCards.tsx
This PR fixed the `firstNonHeaderRowCss` style for GridTables using the `as="virtual"` rendering engine. 
**Important Changes**:
- When using a `virtual` GridTable with `nestedCards` styles, we noticed that there was an extra Chrome row included at the start of the table list. This was due to the `VirtualRoot` not compensating for Chrome rows in this scenario. Resolved the Chrome rows to be pushed to both the `headerRows` and `filteredRows` arrays.
**Before**
**After**
- Conditionally add the `firstNonHeaderRowCss` for nestedCard styles situation to not add these styles to the header.
- Refactored nestedCard.tsx to more clearly expose the row buffer being updated.
- Fixed console.error from React regarding missing `key` props
This was tested using the Storybook Performance addon using _1 …
=> fix: `firstNonHeaderRowCss` for Virtual GridTable

src/components/Icon.tsx, src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/SortHeader.tsx, src/components/Table/sortRows.test.ts, src/components/Table/sortRows.ts, src/components/Table/useSortState.test.ts, src/components/Table/useSortState.ts
GridTable sorting state now toggle between ASC -> DESC -> Initial Sort State. For client side sorting, the initial sort is defined either by the specified initial sort, or as the first sortable column.
For server side sorting we do not define an initially sorted column if it was not specified, (i.e. we do not look for a "first sortable column"). This gives the ability for server side sorting implementations to handle an `undefined` sort state. For use cases like Blueprint's Schedule V2, this allows the table to handle it's sorting reset via: 
```
<GridTable sorting={{ on: "server", value: undefined, onSort: (sortState) => { 
if (sortState[0] === undefined) { 
// reset to original list
} else {
// sort tasks locally
}
}} />
```
Granted, this now requires Blueprint's Schedule V2 table to do …
=> feat: Reset to initial sort state for GridTable

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx
[SC-11802](https://app.shortcut.com/homebound-team/story/11802/remove-use-of-css-grid-in-gridtable)
=> feat: Remove use of CSS grid from GridTable

src/components/Table/GridTable.tsx, src/components/Table/SchedulesV2.stories.tsx, src/components/Table/nestedCards.test.tsx, src/components/Table/nestedCards.tsx, src/components/index.ts, src/utils/rtl.tsx
Perf Test results on the "Nested Cards Three Levels" story:
=> fix: Nested GridTable leaf cards draw their own borders

src/components/Button.stories.tsx, src/components/Button.test.tsx, src/components/Button.tsx
Adding the 'download' prop will:
1. Default to the 'download' icon
2. Use an anchor tag with the 'download' prop
3. Omit the 'linkExternal' icon that is typically supplied with absolute URLs
The 'omitExternalIcon' prop was meant to give the option for remove this default behavior for a download sort of link. Though, this resulted in opening a new tab to trigger a download. Since there are multiple behaviors we want changed when we have a 'download' type of link, the we are creating a single prop to signal those modifications.
=> fix: Remove 'omitExternalIcon' prop in favor of 'download' prop

src/components/Chip.tsx, src/components/Chips.tsx, src/components/PresentationContext.tsx, src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx, src/components/Table/Table.qa.stories.tsx, src/components/Table/columns.tsx, src/components/Table/styles.tsx, src/inputs/TextFieldBase.tsx
Includes a first pass at the following styles:
- Fixed: All rows have a fixed height and content will overflow with an ellipsis if the column is not wide enough to contain it. Provides a 'title' attribute on cells that only contain a string so the browser can provide the built in 'tooltip'.
- Flexible: Content within cells can wrap and will have 16px of padding on top and bottom.
- Nested: Provides a 'groupRowStyle' for providing parent when there is for a nesting depth of 2. Working off of the Budget table example. This can be used along side the Fixed or Flexible row styles.
=> feat: Beam Table Styles

src/components/Tooltip.test.tsx, src/components/Tooltip.tsx
The `children` prop was previously ReactElement was was require because we used 'cloneElement'. We no longer clone the element and can now allow for more types to be passed along such as strings.
Additionally adds the 'title' prop to the wrapping element when the tooltip is not showing and only if the title is of type string. This is to help with testing purposes and follows a similar pattern found from MUI.
=> fix: Allow Tooltip children to be ReactNode, which includes strings

src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/Table.qa.stories.tsx, src/components/Table/styles.tsx
Also updates group styles typography to be xsEm instead of smEm. Updates Storybook example to use `typeScale` prop for setting a specific row kind's column typography. This allowed for changing the font size on a single cell without having to nest it with additional elements. The nesting can circumvent the `PresentationContext.wrap`/truncation styles applied.
Also adds support for min-width definition on GridColumn
=> fix: Support adding typeScale to a specific kind's column cells

src/components/Layout/ScrollableParent.tsx
This seemed like it was doing more harm than good.
=> fix: Remove 'overflow: overlay' as it can sit on top of padding/content

.circleci/config.yml, package.json, release.config.js, yarn.lock
https://app.shortcut.com/homebound-team/story/13496/regenerate-ci-npm-tokens
Our previous NPM token was quite old (2 years) and likely widely exposed before https://github.com/homebound-team/graphql-service/pull/2101 was merged.
This PR updates the CircleCI config to use two distinct `npm` contexts (read-only and publish). This reduces the risk of accidentally publishing in a step that should not. Additionally, it uses a new automation-type token that allows us to enable 2-Factor Auth for login but not for the publishing token.
Once I transition our projects, I will delete the old `npm` context.
=> chore: SC-13496 update NPM contexts

src/components/Table/GridTable.tsx, src/components/Table/Table.qa.stories.tsx, src/components/Table/styles.tsx
The new `beamFixedStyle` didn't work with our old `indent: ...` way of applying "out-of-the-box" parent/child styling, and instead used manually applied row styles like:
```
const rowStyles = useMemo(() => ({ parent: { cellCss: beamGroupRowStyle } }), []);
<GridTable<BeamNestedRow>
style={beamFlexibleStyle}
sorting={{ on: "client" }}
columns={beamNestedColumns}
rows={beamNestedRows}
rowStyles={rowStyles}
stickyHeader
/>
```
This was fine, but I wanted something more out-of-the-box, so this adds a specific `beamNestedFixedStyle` that uses a new `GridStyle.levels` map of level to style, so the usage is now:
```
<GridTable<BeamNestedRow>
style={beamNestedFlexibleStyle}
sorting={{ on: "client" }}
columns={beamNestedColumns}
rows={beamNestedRows}
stickyHeader
/>
```
I.e. the extra `rowStyles` …
=> feat: Add beamNestedFixedStyle.

src/inputs/RichTextField.test.tsx, src/inputs/RichTextField.tsx
Working example of the issue:
* Spam refresh on this page and the text will nondeterministically pop in and out of the textboxes https://blueprint.dev-homebound.com/development-commitments/dc:197?filter=%7B%7D&tab=scheduleAndScope
Some combination of Async Initialization and stale closures were leading to cases where, more often than not, either `editor.current` was undefined, or `value` was undefined.
* The useEffect would bail due to an undefined `editor.current` (After triggering from an external `value` update)
* And `value` would be `undefined` during the onEditorInit block
This change switches `editor` from a Ref to State so that **onEditorInit can trigger a rerender**, at which point the useEffect can do its job and re-sync the `value`
We're abusing useMemo, which is intended to …
=> fix(rich-text-field): async init had issues

src/components/Table/CollapseToggle.test.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/RowState.ts, src/components/Table/SchedulesV2.stories.tsx, src/components/Table/Table.qa.stories.tsx, src/forms/BoundCheckboxField.tsx, src/inputs/Checkbox.stories.tsx, src/inputs/Checkbox.test.tsx, src/inputs/Checkbox.tsx
Leverages the new mobx-based `RowState` to add a map of `rowId` --> `checked | unchecked | partial`.
Uses the `Checkbox` `indeterminate` support to show partially-selected parents as indeterminate.
Handles clicking a parent --> make all children equally selected/unselected.
Handles clicking a child --> recalc it's parents "are you all/none/partially selected", recursively.
=> feat: Add selected row support to GridTable.

src/components/Table/CollapseToggle.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/RowState.ts, src/components/Table/SchedulesV2.stories.tsx, src/components/Table/SelectToggle.tsx, src/components/Table/Table.qa.stories.tsx, src/components/Table/columns.tsx, src/components/Table/index.ts, src/components/Table/visitor.ts, src/utils/useTestIds.tsx
Export `SelectToggle` so that it can be used directly downstream in Blueprint.
Also make the `selectColumn` smarter such that, unless users need to override specific row kinds (i.e. for a totals row that is not selectable), then merely `selectColumn()` will do the right thing and provide a `SelectToggle` for each of the table's row kinds.
...
I also did the same thing for `collapseColumn`.
And also added a `GridTableApi.getSelectedRows` (in addition to the current `GridTableApi.getSelectedRowIds`).
=> feat: Export SelectToggle, make selectColumn provide by default.

src/components/Table/styles.tsx
Updates fallback message styling 
<details><summary>From...</summary>
</details>
To this:
I also wanted to update the Fallback message from `string` to `ReactNode` but that started to cascade and I didn't feel it was worth the trouble right now.
=> chore(grid-table): fallback message styling

src/components/Table/GridTable.stories.tsx, src/components/Table/styles.tsx
The updates provided by #484 were getting overridden when used in conjunction with `beamFlexibleStyle`. This fixes that, and slightly shrinks the padding for the Condensed style as well.
=> fix(grid-table): correct style util fallback styling

src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx
To easily ask for e.g. only children and skip the header + group rows that are selected.
Existing methods to get all:
```typescript
expect(api.current!.getSelectedRowIds()).toEqual(["p1", "p1c1", "p1c1g1"]);
expect(api.current!.getSelectedRows()).toEqual([rows[1], rows[1].children![0], rows[1].children![0].children![0]]);
```
New methods to get by kind:
```typescript
expect(api.current!.getSelectedRowIds("child")).toEqual(["p1c1"]);
expect(api.current!.getSelectedRows("child")).toEqual([rows[1].children![0]]);
```
The return type of `getSelectedRows("child")` will also be narrowed to the specific ADT type, i.e. if it was `type Row = HeaderRow | ParentRow | ChildRow`, the return value will be `GridDataRow<ChildRow>`, so the caller can access any child-specific data.
=> feat: Add kind filters to selected rows.

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/RowState.ts, src/components/Table/Table.qa.stories.tsx
Updates include:
- Selected state for parent rows is rederived when child rows change (either by filter or adding new)
- Selecting a parent element only selects visible child rows
- When filtering, parent rows remain in the filtered list if any of their children match the filter. This keeps the nested structure intact.
=> feat: GridTable improvements

src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/sortRows.ts, src/components/Table/useSortState.ts
We allow setting `sorting` to a non-stable / inline hash:
```
<GridTable
columns={columns}
// And there is no initial sort given
sorting={{ on: "client" }}
rows={rows}
/>
```
But had been using `sorting` in several deps arrays.
=> fix: Fix sorting prop may not be stable.

.github/workflows/conventional-commit-pr-title.yml
Catches when people fix the PR title, but the commit message doesn't have it.
=> chore: Set validateSingleCommit.

src/components/Table/CollapseToggle.test.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/GridTableApi.ts, src/components/Table/RowState.ts, src/components/Table/SchedulesV2.stories.tsx, src/components/Table/Table.qa.stories.tsx, src/components/Table/index.ts
We have a chicken-vs-egg condition with our current GridTable ref-based approach:
```
const api = useRef();
// can't actually use the api yet...
const count = useComputed(() => ..., [api]);
// now api will be set, but we'll only know about it after either
// a useEffect or a re-render.
return <GridTable api={api} />;
```
The "refs are only set after DOM elements are available" makes a lot of sense for DOM elements.
But we want the function to have immediate access to the GridTable API, to set up reactivity on things like which rows are selected.
To provide this, we just let the caller instantiate the api directly:
```
const api = useGridTableApi();
// Can immediately use it
const count = useComputed(() => api.selectedRows.length, [api]);
// Pass it to GridTable
return <GridTable api={api} …
```
=> feat: Add useGridTableApi hook as a better ref

src/inputs/DateField.mock.tsx, src/inputs/DateField.stories.tsx, src/inputs/DateField.tsx, src/inputs/NumberField.stories.tsx, src/inputs/NumberField.tsx, src/inputs/TextAreaField.stories.tsx, src/inputs/TextAreaField.tsx, src/inputs/TextField.stories.tsx, src/inputs/TextField.tsx, src/inputs/TextFieldBase.tsx, src/inputs/internal/SelectFieldInput.tsx, src/interfaces.ts
Adds support for displaying tooltips via the 'disabled' or 'readOnly' props for:
- TextField
- TextAreaField
- NumberField
- DateField
These follow the pattern already in place by SelectField and MultiSelectField.
With this PR, all components that utilize TextFieldBase now support tooltips via the readOnly and disabled properties
=> feat: Expand support of tooltips via disabled and readOnly

src/components/PresentationContext.tsx, src/components/Table/GridTable.tsx, src/components/Table/Table.qa.stories.tsx, src/components/Table/styles.tsx, src/forms/formStateDomain.ts, src/inputs/TextFieldBase.tsx, src/interfaces.ts
Changes include:
- Input fields no longer use box-shadow for focus state when 'borderless'
- New presentation prop for fields: 'errorInTooltip'. Allows the error message to display in a tooltip instead of beneath the field.
- 'borderless' presentation prop is defined for Flexible table styles as well.
- Adds 'internalProps' for TextField to allow for forcing hover and focus states for snapshot purposes.
Adds story for fields in a table in their various states.
=> fix: Update input field styles in tables

src/components/Table/CollapseToggle.tsx, src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/SchedulesV2.stories.tsx, src/components/Table/Table.qa.stories.tsx, src/components/Table/columns.tsx, src/components/Table/sortRows.ts, src/components/Table/styles.tsx
Includes UX for a third level of nesting in GridTable.
Changes include:
- Collapse Toggle to use 'compact' variant if already nested
- Apply 'tiny' type scale for first non-action column for further visual difference between 2nd and 3rd level of nesting.
=> feat: Update to nesting styles for Table component

package.json, src/components/Layout/ScrollableContent.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/utils/rtl.tsx, src/utils/shallowEqual.ts, yarn.lock
This should dramatically increase the effectiveness of our per-row
memoization, given that otherwise basically any re-calc of the
GridTable.rows prop (due to new rows/different group by/etc)
would invalidate every single row, and not just the ones with
changed `data` props.
Note that this is now only possible b/c of our recent PR to double
down on `GridDataRow.data` as required for all tables, and not
interleaving "misc data" directly into the `GridDataRow`.
=> fix: Memo on GridDataRow.data instead of the row itself.

package.json, src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx, src/inputs/internal/VirtualizedOptions.tsx, yarn.lock
This fixes an issue where sticky columns were layering on top of the sticky header when virtualized.
Uses the Virtuoso's 'TopItemList' component to apply styling directly to the TopItemList vs the rest of the list.
=> fix: Virutalized table sticky header to apply zIndex of 2

src/components/internal/Menu.tsx
The 'restoreFocus' causes React-Aria to try and retain focus on the element which triggered the Menu component. Though, if the menu closed in order to open a Modal, then we have conflicting signals to React Aria as to where focus should go - either in the Modal or back to the Menu's trigger. Removing 'restoreFocus' to no longer attempt to put the focus back to the Menu's button once closed. Will follow up with the Adobe team to provide this example and ask for guidance on how to go about this sort of behavior.
=> fix: Do not 'restoreFocus' on Menu when it closes

.storybook/preview.tsx, package.json, src/Css.ts, src/components/Button.stories.tsx, src/components/Button.tsx, yarn.lock
**Note:** Design only provided primary and tertiary variants of buttons for 'contrast'/dark mode. Since the "text" variant is extremely similar to "tertiary", then I followed suite on those stylings. Secondary, danger made some slight modifications, but didn't want to spend too much guess work on it until design comes back with updates for these.
=> feat: Support contrast variant of Buttons

src/components/Button.stories.tsx, src/components/Button.test.tsx, src/components/Button.tsx, src/components/IconButton.stories.tsx, src/components/IconButton.test.tsx, src/components/Modal/Modal.stories.tsx, src/components/SuperDrawer/SuperDrawer.stories.tsx, src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx, src/components/internal/OverlayTrigger.tsx, src/inputs/Examples.stories.tsx, src/interfaces.ts, src/utils/getInteractiveElement.tsx
By utilizing the new prop, then GridCells can properly truncate text when the rowHeight is fixed. This prevents users having to ensure they add proper truncation styles locally when wanting to wrap the content of the cell in an interactive element
=> feat: Add GridCellContent.onClick property to easily wrap content in a link/button component

src/components/Layout/Layout.stories.tsx, src/components/Layout/ScrollableParent.tsx, src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx
Adds 'min-width: fit-content' to GridTable when rendered as="div". This ensures the container in which the sticky columns live is as wide as the table's contents and prevents the columns from becoming 'unstuck' prematurely.
Changes `padding-left` to `margin-left` in the ScrollableParent to ensure content that scrolls horizontally doesn't bleed through the left padding.
=> fix: Ensure sticky columns do not become unstuck

jest.config.js, package.json, src/components/Table/GridTable.test.tsx, src/components/Table/RowState.ts, yarn.lock
Code had assumed that the 'header' was always in the first position of the 'collapsedIds' array. However, we always just pushed the 'header' into the array, so if the header was not the first row to be collapsed then the logic would break. To fix we now check if the array includes 'header' rather than expecting it in the first position.
Additionally updated the header's collapse toggle behavior to update depending on the state of every top level collapsible row.
Adds tests for the bug fix and for the new header behavior.
=> fix: Bug fix for toggling collapse state

src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/GridTableApi.ts, src/components/Table/RowState.ts
Adds new property on GridDataRow, 'initCollapsed'. By setting this to true it will signal to the table to initially render this row as collapsed. As the name describes, this is only applied/read on initial render. If the user has also set up the 'persistCollapse' then any values available in the localStorage will trump those set on GridDataRow.
Includes tests
=> feat: Support setting group rows as initially collasped

src/components/Modal/Modal.tsx
Blueprint's To Do modal includes a list of attachments. These attachments can be images that trigger a 3rd party lightbox component, that was closing both the modal and the lightbox component if you interacted with the lightbox.
This PR allows for keeping the modal open if the user is interacting with another dialog on top of it.
=> fix: Modal should not close if interacting with another dialog ontop of it - such as a Lightbox

package.json, src/components/BeamContext.tsx, src/components/Modal/Modal.tsx, src/components/SuperDrawer/SuperDrawer.tsx, yarn.lock
Adds AutoSaveStatusProvider back in, backed by `@homebound/form-state` upgrade
Already did the `npm run watch-beam` and `yarn ttsc -w` stuff to test it on BluePrint ✅
=> fix: auto save status provider

src/components/internal/DatePicker/Day.tsx
=> fix: 'Today' bgColor should be overwritten if 'selected'

src/components/Snackbar/Snackbar.tsx
Moving to bottom left instead of bottom right as we're planning to float the Help Center icon to the bottom right
=> fix: Move snackbar to bottom left

src/components/Stepper.tsx, src/forms/StepperFormApp.tsx
Updates progress bar to be calculated based upon provided `step`'s `status` to unblock Lot Config / Lot Release work - [Lot Config / Lot Release PR](https://github.com/homebound-team/internal-frontend/pull/2195)
- Progress calculated in accordance to provided `step`s completion status:
- if provided `step`'s 3rd step is the last step to have its `state === "complete` then progress bar is set to it's index, e.g. 2
- if no step has a `state === "complete"` then progress is reset (set to `-1`)
=> feat: Stepper Progress Bar Update

src/inputs/NumberField.stories.tsx, src/inputs/NumberField.test.tsx, src/inputs/NumberField.tsx
Pass at allowing more generic number formatting beyond what's specified via `type`
=> feat: allow passing numberFormatOptions to override number formatting

src/components/NavLink.stories.tsx, src/components/NavLink.tsx
As part of the design of [SC-17566](https://app.shortcut.com/homebound-team/story/17566/new-development-level-navigation) there's need to add a contrast prop to NavLink side variant.
=> feat: add NavLink side contrast variant

src/components/NavLink.stories.tsx, src/components/NavLink.tsx
The prop wasn't working as expected as Alex told me in this comment https://github.com/homebound-team/beam/pull/566#issuecomment-1164750843, I was checking on the wrong storybook, this is now fixed with this PR and works as expected.
=> fix: NavLink contrast prop not working

src/components/Stepper.tsx
- [sc-18471](https://app.shortcut.com/homebound-team/story/18471/update-stepper-to-be-more-responsive)
- use `min` and `max` widths to calc list items widths
- add `gap`
=> feat: Responsive Stepper

src/components/Table/GridTable.test.tsx, src/components/Table/sortRows.test.ts, src/components/Table/sortRows.ts
I.e. to put all of the favorited documents first, but then within
those still sort by the given column.
This basically becomes a way to add an "always on" first sort.
=> feat: Sort within pinned rows.

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/GridTableApi.ts, src/components/Table/SelectToggle.tsx, src/components/Table/columns.tsx, src/inputs/CheckboxBase.tsx
- [sc-18644](https://app.shortcut.com/homebound-team/story/18644/update-gridtable-api-selection-to-exclude-disabled-selections)
- update checkbox style to show checkmark when selected and disabled
- update selection logic to exclude rows that are not `selectable`
- expose `disabled` prop in `selectToggle` to be able to display disabled state
=> feat: handle disabled selections

src/components/Chip.tsx, src/components/ToggleChip.stories.tsx, src/components/ToggleChip.tsx
Chips only support two sizes, so rather than supporting any typescale, define type scale on 'compact' or not.
=> feat: Support compact ToggleChips

src/inputs/NumberField.tsx
`<NumberField />` already drills through `{...otherProps}` to the underlying TextFieldBase, but the TS Type doesn't like `clearable` because it's not declared.
I started down the avenue of having NumberFieldProps extend TextFieldBaseProps but it started to spiral and I want a quick win. It was starting to look like `extends Omit<TextFieldBaseProps<Xss<"justifyContent" | "textAlign">>, "onChange">` but then there were issues with `inputProps={inputProps}` "always being overridden by the spread of `{...otherProps}`" and I opted for path of least resistance.
I can reattempt `extends` if there's demand for it, otherwise this is a cheap free win and I'm here for it.
=> fix(number-field): expose `clearable` prop

src/inputs/DateFields/DateField.stories.tsx, src/inputs/DateFields/DateFieldBase.test.tsx, src/inputs/DateFields/DateFieldBase.tsx
[SC-18436](https://app.shortcut.com/homebound-team/story/18436/remove-calendar-icon-from-schedule)
Straightforward implementation of optional bool property. 
- `DateFieldBase` will not pass `calendarButton` to start/end adornment prop in any way if this value is true. This will eliminate any extra padding in the input field.
- Added a simple test and story view.
=> fix: Add optional param to DateFieldBase to hide calendar icon

src/components/Table/GridTable.test.tsx, src/components/Table/sortRows.test.ts, src/components/Table/sortRows.ts
I'd broken the behavior of the Change Events v2 line items page, which uses `pin: last` for two different uses:
* A group of "just added" CELIs that we don't want strewn all over the table by a sort, instead we want the user to see/work them in order
* The very last "add inline" psuedo CELI
And if we "sort within pins", then the "add inline" CELI can get reordered amongst the "just added" CELIs.
I had originally written this for @aTrujilloHomeBound to potentially use for "favorite documents", but they ended up not being able to use `pin`s anyway, b/c pinned rows are not filtered, and they needed favorite documents to still have filters applied to them.
=> fix: Revert "feat: Sort within pinned rows. (#581)"

src/components/SuperDrawer/SuperDrawer.stories.tsx, src/components/SuperDrawer/SuperDrawer.tsx, src/components/SuperDrawer/SuperDrawerContent.tsx, src/components/SuperDrawer/index.ts, src/components/SuperDrawer/useSuperDrawer.tsx, src/components/SuperDrawer/utils.ts
With this PR a `width` option will be added to the `openInDrawer` from the `useSuperDrawer` hook, when this option is set to `"small"` it will set the SuperDrawer width to `560px`, if this prop is not passed the width will default to `1040px`.
```javascript
// Example from `SuperDrawer.stories.tsx`
openInDrawer({
title: "Drawer Title",
content: <TestDrawerContent book={Books[0]} />,
width: "small"
});
```
=> feat: added `Small` width prop for SuperDrawer

src/components/Chip.stories.tsx, src/components/Chip.test.tsx, src/components/Chip.tsx
[#19307](https://app.shortcut.com/homebound-team/story/19307/chip-configuration)
Added `type` prop to  `Chip` component with styled values of `caution, warning, success`
=> feat: add type to chip

src/components/Icon.stories.tsx, src/components/Icon.tsx
This icon contains hard-coded attributes since our current Icon/IconButton don't support any stroke property for changing it (@bdow should I implement this instead of hard-coding those values?).
=> feat: add outline-flag icon

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx
[SC-19741](https://app.shortcut.com/homebound-team/story/19741/beam-add-revealonhover-to-beam-tables)
- Adds ability to reveal a cell on row hover
=> feat: reveal on row hover

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx
In GridTable, when rendering a cell as a button, the content was becoming center aligned due to browser defaults for the <button> element. Adding 'text-align: "inherit"' to ensure the alignments set on the cell reflect the content.
=> fix: Ensure interactive elements inherit the text alignment

src/components/ButtonMenu.tsx, src/components/internal/MenuItem.tsx
Adding forceSameBrowserTab to MenuItemBase to allow safari to open the link provided in the same browser window.
Explanation:
`window.open(url, "_blank", "noopener,noreferrer")` works as expected on all main browser, but with safari there is a particular behavior.
in Safari -> Preferences -> Tabs -> Open pages in tabs instead of windows is set to `Automatic`. Using the `features` param in `windown.open` makes the browser to open a new tab.
Adding this param makes the button to use the `window.open(url, target)` syntax, that gets by default a new tab behavior, and forces the `opener` to null to prevent exposin the origin window tab. As a caveat, this does exposes the referrer.
This behavior is also overridable if safari option is set to `Never` or `Always` so is not that `forced` really. …
=> feat: [SC-20356]  forceSameBrowserTab to make safari open link in same window

src/components/Table/styles.tsx
Moving from 16px of padding on top and bottom to 12px in hopes to eliminate unnecessary white-space.
=> fix: Update vertical padding on flexible row height

src/components/Chip.stories.tsx, src/components/Chip.test.tsx, src/components/Chip.tsx, src/components/Chips.stories.tsx, src/components/Chips.tsx
[SC-19452]
Based on the requirement to have the chip title to display detailed information different than the chip content, we are adding support for a object having text and title properties, adding also unit tests and stories to cover this usage
=> feat: [SC-19452] Chip custom title support

src/components/Layout/ScrollableContent.tsx, src/components/Layout/ScrollableParent.tsx
In Blueprint there are pages such as Documents and To Dos which nest their scroll handling. There are potentially better ways to achieve this, but the simplest way at the moment is using this prop.
=> fix: Ability to omit bottom padding from ScrollableContent

src/components/Layout/ScrollableContent.tsx
This fixes issues where users may have a Virtualized component within the ScrollableContent, but forgot to set the ScrollableContent.virtualized prop
=> fix: Always apply 'h100' on ScrollableContent wrapper

src/components/Avatar.stories.tsx, src/components/Avatar.tsx
Also allow name to not be set and fallback to the user circle icon.
After updating this in Blueprint it was clear the `name` property may not always be available. Updating upstream to handle these cases better.
=> fix: Bug fix for Avatar when name is empty string.

src/components/Icon.tsx, src/inputs/TextFieldBase.tsx
The conditional wrapping of the tooltip when a textfield is in error causes some usability issues. Specifically, when the field is in error and the user then corrects the problem, it will rerender removing the conditional Tooltip wrapper. This rerender loses focus on the input, which can be very annoying for users.
Updating this error state to be inline with what is design for [Beam](https://www.figma.com/file/aWUE4pPeUTgrYZ4vaTYZQU/%E2%9C%A8Beam-Design-System?node-id=1944%3A14)
=> fix: Textfield 'errorInTooltip' to show the tooltip on an icon, not the whole field

src/inputs/NumberField.stories.tsx, src/inputs/NumberField.test.tsx, src/inputs/NumberField.tsx, src/inputs/TextFieldBase.tsx
Also adds missing support for 'placeholder' on NumberField and allows for a user to define `errorInTooltip` outside of PresentationProps
=> feat: Support numIntegerDigits on NumberField

src/components/Table/GridTable.tsx, src/components/Table/Table.qa.stories.tsx, src/components/Table/TableActions.tsx, src/components/Table/TableStyles.tsx
Changes include:
- Allows for adding a border around the table
- Allows for having the table all white, which also applies a 8px border radius on the table corners.
- Moves TableActions component to Beam from internal-frontend
Added a new Storybook for the Design QA that allows them to use the controls to see different instances of the table.
=> feat: SC-22182 - Support white background on table

src/components/Table/GridTable.tsx, src/components/Table/Table.qa.stories.tsx, src/components/Table/TableStyles.tsx, src/components/Table/components/Row.tsx
Hover styles can be optionally removed in the event it is too distracting.
=> feat: GridTable shows row background on hover by default

src/components/Table/components/SortHeader.tsx, src/components/Table/utils/utils.tsx
When implementers use SortHeader directly, they are typically doing it in the middle of building their column and so cannot pass the column prop. Example:
```
const homeownerOriginalColumn = numericColumn<Row>({
header: () => (
<Tooltip placement="top" title="The budgeted cost from the prime contract">
<SortHeader content={initialBudget.replace("Budget", "")} iconOnLeft />
</Tooltip>
),
```
Instead, we now only require passing the sortKey string, which should be accessible at this point
=> fix: Do not pass whole column to SortHeader, only sort key

package.json, src/Css.ts, yarn.lock
- bumping beam to have the new truss breakpoint exports - truss v1.115.0
=> fix: Bump Truss

src/components/Tag.stories.tsx, src/components/Tag.test.tsx, src/components/Tag.tsx
Changes in Tags include:
- muting the background colors
- adjusting the padding to make them smaller
- supporting the ability to add an icon if desired
=> feat: add Icon to Tags (sc-22870)

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTableApi.ts
Updates GridTableApi to include a function to toggle collapse row.
This update needed for this ticket (https://app.shortcut.com/homebound-team/story/24301/linked-rows-on-create-flow)
=> feat: (SC-24529) Add toggleCollapse to GridTableApi

src/forms/StaticField.stories.tsx, src/forms/StaticField.tsx
Update the StaticField to reuse on this design to pass a ReactNode on the label in this case we need a combination label and buttonModal
Figma
Storybook
=> feat: StaticField Label has the ability to show ReactNode

src/components/Accordion.stories.tsx, src/components/Accordion.test.tsx, src/components/Accordion.tsx, src/components/AccordionList.test.tsx
No longer use max-height for animating as it results in inconsistent animation timings depending on size of the content. The proposed way in this PR is to animate the height. We now hide the Accordion's content until it has been expanded. Once expanded and the content is rendered, then a useEffect runs to calculate the contents height. That height is then applied to the wrapping element to animate its height to that of the content. It now requires two renders to complete the animations, but it is much smoother and the second render should be very minimal
=> fix: Improve Accordion height animation

src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/utils/TableState.ts
After attempting upgrade Beam in internal-frontend, I noticed the Project Schedule's EditColumnsButton + useColumns implementation used a custom session storage key to differentiate the visible column states between project stages. This PR adds that ability back and updates tests.
=> fix: Support custom storage key for visible columns

src/inputs/TextFieldBase.tsx
Adding an extra condition to render the error styles into the beam input fields, so the red border with only display if the field is enabled, following the same pattern that we have when hidding the error message if the field is disabled
ex.
after the fix
=> fix: [SC-24684]  Removing error styles on disabled inputs

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/components/Row.tsx, src/components/Table/hooks/useSetupColumnSizes.ts, src/components/Table/types.ts, src/components/Table/utils/columns.tsx
Two issues addressed:
1. Columns should be expandable to a larger width, they do not necessarily need to show more columns. Updated so 'expandColumns' prop can accept a number value, which is used as the pixels to grow the column to.
2. Virtualized GridTable forgot to account for the expandable header when calculating the total number of rows.
=> fix: Expandable Column fixes

src/inputs/NumberField.tsx
[SC-22763](https://app.shortcut.com/homebound-team/story/22763/inline-editing-predecessors-successors)
Needed to override the background color of the field
=> feat: Add borderless to NumberField

src/components/ButtonModal.test.tsx, src/components/ButtonModal.tsx, src/components/internal/ContextualModal.stories.tsx, src/components/internal/ContextualModal.tsx, src/components/internal/OverlayTrigger.tsx
Allows for the ButtonModal's content to provide its own closing actions
=> feat: Pass 'close' method to ButtonModal content

src/components/Filters/Filters.stories.tsx, src/components/Filters/NumberRangeFilter.test.tsx, src/components/Filters/NumberRangeFilter.tsx, src/components/Filters/index.ts, src/components/Filters/testDomain.ts, src/inputs/NumberField.tsx
Created a new number range filter type that allows users to set `min` and/or `max` number range values.  The new filter is set up to render two separate layouts for vertical or horizontal.
- Created the new `NumberRangeFilter` component
- Created unit tests for new component
- Updated the Filter story to include the new number range filter
- Updated `NumberField` to allow new props - `sizeToContent` & `inlineLabel`
Vertical View:
Horizontal View:
=> feat: [SC-24998]  Create number range filter type

src/components/Table/GridTable.tsx, src/components/Table/components/Row.tsx
Whether rendering as virtual, a table, or by default, all header rows (Totals, Expandable Column headers, and regular column header) are contained in a single element. This allows to have more percise styling and eliminates the need to define a 'stickyOffset' per header row when 'stickyHeader' is defined.
=> chore: Reorganize Table header rows into a single container

src/components/BeamContext.tsx, src/components/ButtonGroup.tsx, src/components/SuperDrawer/SuperDrawer.stories.tsx, src/components/SuperDrawer/SuperDrawer.tsx, src/components/SuperDrawer/components/SuperDrawerHeader.tsx, src/components/SuperDrawer/index.ts, src/components/SuperDrawer/useSuperDrawer.test.tsx, src/components/SuperDrawer/useSuperDrawer.tsx, src/forms/SuperDrawerApp.stories.tsx, src/inputs/Examples.stories.tsx
Introduces the SuperDrawerHeader component. This component portals itself into the header of the SuperDrawer. Follows the existing pattern of our Modals.
This is a fairly large breaking change as we have completely changed how to define the header of the SuperDrawer. It removes all title/header configuration properties from the openInDrawer method.
=> feat: SuperDrawerHeader

src/components/Button.stories.tsx, src/components/Button.test.tsx, src/components/Button.tsx, src/components/Loader.stories.tsx, src/components/Loader.tsx
[SC-25242](https://app.shortcut.com/homebound-team/story/25242/fe-beam)
Spending Hackday updating some libraries and doing cleanup for Underwriting app. 
The async button changes felt like a natural progression since we're automatically disabling it in flight already.
=> feat: HackDay: Add xs loader; Button allow change icons on async

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/utils/simpleHelpers.ts
eslint doesn't like the `{}` type.
=> fix: Use undefined for simpleHeader.data.

src/components/ButtonGroup.stories.tsx, src/components/ButtonGroup.tsx
=> fix: Fix styling of button group when using tooltips

src/components/ButtonGroup.stories.tsx, src/components/ButtonGroup.tsx
In Blueprint, the Schedules page was reaching into the component to make the button group smaller. This caused problems when changing the markup of the ButtonGroup component. Instead of trying to rework those styles reaching into Beam, we are not supporting a smaller size.
=> feat: ButtonGroup 'xs' size

src/components/ButtonGroup.tsx
In the below examples, the line-height is being inherited from the ModalHeader component, causing `<span/>` elements that wrap each button to be taller than they should.
=> fix: Avoid inheriting line-height in ButtonGroup

src/components/Filters/CheckboxFilter.test.tsx, src/components/Filters/CheckboxFilter.tsx, src/components/Filters/Filters.stories.tsx, src/components/Filters/testDomain.ts
* Adds a new `checkboxFilter` to Beam's Filter components
* Behaves similar to `toggleFilter`, but using a checkbox instead
=> feat: SC-24760 Add checkbox filter

src/components/Filters/index.ts
- Accidentally left out the export to use the new `CheckboxFilter`
=> fix: Add export to Checkbox Filter

src/components/Filters/NumberRangeFilter.tsx
Story details: https://app.shortcut.com/homebound-team/story/26428
We're using numberRangeFilter for a year value and dont need the formatting. This is a quicker fix than updating the DatePicker to have a year-only option  and bubbling that up to be useable by a DateRangeFilter component
=> fix: [sc-26428] Expose numberFormatOptions prop in NumberRangeFilter;

src/components/Table/GridTable.test.tsx, src/components/Table/components/Row.tsx, src/components/Table/utils/TableState.ts
When adding `GridDataRow.inferSelectedState: false` to a row, then it will no longer derived its selected state based on the state of its children rows. Instead the row must be selected specifically (or via its own parent) in order for it to be considered selected. This also removes the ability for the row to show in the 'indeterminate' state
=> feat: Allow parent rows to be selected independent of child row selections

src/components/Table/utils/TableState.test.ts, src/components/Table/utils/TableState.ts
For Bulk Template Management, whenever we touch a cell (delete, save) and trigger a new `createColumns()` call, that trickles through GridTable and TableApi and resets/collapses any expanded columns we had.
By the nature of our table, users will be updating items across the row in quick succession, so having to re-expand a column each time they touch it or its children will get tedious.
Commenting out 220/221 appears to fix it but would likely break the initExpanded feature. So I've scoped it to only run when initially setting the columns. This likely means that if a developer is _toggling_ `initExpanded` in _their_ createColumns for some reason, that likely won't have any effect.
=> fix(grid-table-expanded-cols): persist between rerenders

src/components/Filters/MultiFilter.stories.tsx, src/components/Filters/MultiFilter.tsx, src/components/Filters/testDomain.ts, src/inputs/ToggleChipGroup.test.tsx, src/inputs/ToggleChipGroup.tsx, src/inputs/internal/SelectFieldBase.tsx
Multiselect filter will now correctly disable options when rendered as a ToggleChipGroup.
=> fix: [sc-27302] Multiselect filter correctly disables chips in modal;

src/inputs/RadioGroupField.stories.tsx, src/inputs/RadioGroupField.test.tsx, src/inputs/RadioGroupField.tsx
Changes in RadioGroupField include:
- add optional `disabled` attribute to `RadioFieldOption`
- add optional `disabledTooltip` attribute to `RadioFieldOption`
=> feat: add disabled flag and tooltip to radio group field options (sc-25841)

src/inputs/NumberField.tsx, src/inputs/TextFieldBase.tsx
Allow number field to always show the helper text if the prop `alwaysShowHelperText` is passed.
=> feat: allow to always show helper text

src/components/Layout/Layout.stories.tsx, src/components/Layout/ScrollableContent.tsx, src/components/Layout/ScrollableParent.tsx
Previously setting the bgColor on ScrollableContent was only displaying the background color at 'height: 100%', which applied to only what was in view on the screen. Once the user scrolled, then you could see the background was not under all of the content. Switching to use flex-box and a flexGrow: 1 to have the ScrollableContent's element to extend the full height of the content within.
Additionally removing the bottom padding when using the fallback when ScrollableContent is not used. This is because of issues it causes with setting background colors elsewhere (like on tabs), but then the background is no applied to the ScrollableParent, so the extra padding would not include a background color, and would look weird. It would also be something not easily addressed by the consuming app, …
=> fix: ScrollableContent bgColor bug fix

src/components/Table/GridTable.stories.tsx, src/components/Table/components/Row.tsx, src/components/Table/components/cell.tsx, src/components/Tooltip.tsx
Updated the Tooltip component's wrapping element to use 'display: contents;'. This allows for styles to flow through the element like it wasn't there, such as flex item positioning.
=> feat: Add tooltip support to GridTable

src/components/internal/OverlayTrigger.tsx
It was discovered that on iOS that the OverlayTrigger was not invoking the menu to open. This appeared to be due to passing 'noop' to the trigger element's onClick property. For whatever reason on non-mobile browsers this appeared to still work find. The 'menuTriggerProps.onPress' was still be fired as expected. Though, it was not being fired on iOS. This update passes the 'menuTriggerProps.onPress' as the 'onClick' property of the trigger elements where needed.
Not 100% sure how to go about adding a regression test at the moment, but figured we can get this fix out in the meantime.
=> fix: OverlayTrigger to pass onClick value

src/components/Filters/MultiFilter.tsx
BulkTemplateManagement asks people to select filters first, before loading any data. It's disjoint for the filter to say "All" when Nothing is selected or loaded, and `multiFilter({})` is ignoring nothingSelectedText.
=> fix: use nothingSelectedText on MultiSelectField

src/hooks/useComputed.ts
Not sure why I didn't think of adding this before.
Should fix the "cannot call setState on an unmounted component errors" we see in tests sometimes.
=> fix: Unsubscribe on unmount.

src/hooks/useComputed.ts
This seems a little odd IMO, but it was a feature of the Blueprint `useComputed` that I want to remove.
It was used like:
```ts
const useQuantity = useComputed(
(prev) => {
const uomId = formState.unitOfMeasureId.value;
const uom = unitsOfMeasure.find((uom) => uom.id === uomId);
const curr = !uom ? true : uom.useQuantity === true;
// If going from useQuantity=false --> useQuantity=true, reset quantity
if (prev === false && curr) {
formState.quantity.set(1);
} else if (prev === true && !curr) {
formState.quantity.set(undefined);
}
return curr;
},
[formState, unitsOfMeasure],
);
```
=> feat: Pass previous value to useComputed.

src/components/Chip.stories.tsx, src/components/Chip.tsx
We need to add a new type style for Chip
As per as conversation with Radhi, the name should be `darkMode`
Figma: https://www.figma.com/file/anwOr1tvzTrXObf3vh2QfX/22-Q3-%F0%9F%9B%A0-Item-Catalog?node-id=5403%3A90038&t=ZUXMT7oeBzScF23w-0
=> style: SC-26626 add darkMode type to chip styles

src/components/Table/GridTable.test.tsx, src/utils/rtl.tsx
Generates a human-readable string representation of a table for easy matching using `toMatchInlineSnapshot`
```ts
expect(tableSnapshot(r)).toMatchInlineSnapshot(`
"
| Name                     | Value |
| ------------------------ | ----- |
| Row 1                    | 200   |
| Row 2 with a longer name | 300   |
| Row 3                    | 1000  |
"
`);
```
**Example from lot sequence sheet:**
```ts
expect(tableSnapshot(r)).toMatchInlineSnapshot(`
"
|     |          |                  |          | Plot information  | Exterior options | Floor plan options | Add-ons          | Interior options   |               |
|     | Address  | Construction RTS | Delivery | Plan              | Spec level       | Sellable SF        | Net Buildable SF | Gross Buildable SF | Permitable SF | Bedrooms | Full …
```
=> feat: add `tableSnapshot` helper

src/forms/StaticField.stories.tsx, src/forms/StaticField.test.tsx, src/forms/StaticField.tsx
- Add support for `labelStyle` prop
Discussion: https://github.com/homebound-team/internal-frontend/pull/3533#discussion_r1131495964
=> feat: support for label style on StaticField

package.json, src/forms/StaticField.test.tsx, src/forms/StaticField.tsx
Fix to https://github.com/homebound-team/beam/pull/824
=> fix: Set width on Static Field when label style is LEFT

src/forms/StaticField.stories.tsx, src/forms/StaticField.tsx
After run Chromic step we could notice a bunch of changes in the PR above, this is because the property `width` set in last commit was wrong.
PR (https://github.com/homebound-team/internal-frontend/pull/3533)
This PR is to remove that and avoid change it in many places.
=> fix: Remove wrong width from Static Field div

src/components/Avatar.stories.tsx, src/components/Avatar.tsx
Includes storybook example as a regression test.
=> fix: Prevent Avatar from squishing by setting min-width

src/components/Filters/MultiFilter.tsx, src/inputs/MultiLineSelectField.tsx, src/inputs/MultiSelectField.tsx, src/inputs/SelectField.tsx, src/inputs/internal/ComboBoxBase.tsx, src/inputs/internal/ComboBoxInput.tsx
Rename the internal component SelectFieldBase and SelectFieldInput to ComboBoxBase and ComboBoxInput in preparation for creating a SelectField without the "type to filter". This will make distinguishing between the internal components easier as one will use React-Aria's 'useComboBox' (existing) and 'useSelect'. 
For extra context, the eventual state is that when using the 'SelectField' component that has fewer than X options, then a user will get the SelectField vs the ComboBox, as the type to filter will be unnecessary. We had said always supplying the "type to filter" wouldn't hurt, but that has become untrue with users on iPads. Currently when a user opens up a SelectField, then the input is immediately focused, triggering the iPad's keyboard, and then limiting the amount of space …
=> chore: Rename internal components

src/inputs/SelectField.test.tsx, src/inputs/SelectField.tsx, src/inputs/TextFieldBase.tsx, src/inputs/internal/ComboBoxBase.tsx, src/inputs/internal/ComboBoxInput.tsx
This provides a better UX for users using iPads where the virtual keyboard gets in the way and is unnecessary for select fields with few options.
=> feat: Disable type to filter for single SelectFields with 10 or fewer options

src/inputs/SelectField.mock.test.tsx, src/inputs/SelectField.mock.tsx
Currently our SelectField mock doesn't support disabled options object, this PR adds the ability to disable an option when it is an object.
=> feat: support disabledOptions object on mock select field

src/components/Icon.stories.tsx, src/components/Icon.tsx, src/inputs/CheckboxBase.tsx, src/inputs/TreeSelectField/TreeOption.tsx, src/inputs/TreeSelectField/TreeSelectField.stories.tsx, src/inputs/TreeSelectField/TreeSelectField.test.tsx, src/inputs/TreeSelectField/TreeSelectField.tsx, src/inputs/TreeSelectField/index.ts, src/inputs/TreeSelectField/utils.ts, src/inputs/index.ts, src/inputs/internal/ComboBoxInput.tsx, src/inputs/internal/ListBox.tsx, src/inputs/internal/Option.tsx, src/inputs/internal/VirtualizedOptions.tsx
Creates new TreeSelectField component that allows nested groupings of items within the menu. Handles updating parent and child options selected state based on user input or values defined. Includes logic for lazily loading options.
Supports all existing states as Beam's other fields (disabled, readOnly, etc), as well as variations (compact, label styles, etc).
Adds tests and stories
Future improvements:
- Generate unique keys for each option based on grouping hierarchy
- Create Bound___Field equivalent
- Create Tree filter field for use within Beam filters
- Look at either moving existing TreeFieldState into either the context that currently only supports the collapsed state, or moving everything into a mobx state. Admittedly, this optimization should probably happen sooner than later. …
=> feat: TreeSelectField

src/components/Table/components/ExpandableHeader.tsx, src/components/Table/components/SortHeader.tsx, src/components/Table/components/cell.tsx, src/components/Table/utils/utils.tsx
When using the `tooltip` property on `GridCellContent`, the 'infoCircle' icon will be displayed as the tooltip trigger/target. This makes it more discoverable when tooltips are added to our table cells.
=> feat: Add icon for denoting tooltips in table cells

src/components/Button.stories.mdx, src/components/Button.stories.tsx, src/components/Button.tsx, src/components/ButtonModal.stories.tsx
[SC-32614](https://app.shortcut.com/homebound-team/story/32614/add-new-button-variant-to-beam-s-button-modal)
* Add new `secondaryBorderless` variant to Button
=> feat: Add secondary borderless button variant

src/components/IconButton.tsx, src/components/internal/MenuItem.tsx, src/components/internal/MenuSection.tsx, src/components/internal/OverlayTrigger.tsx
Prevent Icon and Avatar buttons from adding more height than necessary. Define color for non-contrast menu items (inherited via MenuSection styles) Add 'align-items: center' for MenuItems wrapped in links Add 'label' prop for IconButton for accessibility purposes
=> fix: Various minor style fixes

src/components/ScrollShadows.tsx
Replaces useLayoutEffect for useResizeObserver to fix issue where the content of the ScrollShadows component is lazily loaded, so the whether we show the shadows needs to be reevaluated.
=> fix: Use ResizeObserver on ScrollShadows

src/components/ScrollShadows.tsx
Refactors styles in hopes of not regenerating them every time the state changes / component re-renders
=> fix: Add zIndex to ScrollShadows

src/components/NavLink.tsx, src/components/internal/Menu.stories.tsx, src/components/internal/MenuItem.tsx
Context of the change [SC-34164](https://app.shortcut.com/homebound-team/story/34164/cmd-click-on-menu-items-under-libraries-does-not-open-pages-in-a-new-tab), after that, I made some changes
- Replace react-router-dom <NavLink with  react-router-dom <Link `<a role="button"`, that is the reason of the issue (I searched and only this component was using this version)
- Update the storybook to show all the variations on a menuItems
Please see the video [DEMO BUG/FIX](https://www.awesomescreenshot.com/video/17326734?key=5de1eb65374829ac52f8debc163c7dbc)
[Menu Storybook](https://60466f7d43c37c0021788867-rmtwfusvhr.chromatic.com/?path=/story/workspace-components-menu--basic-menu-items)
=> feat: On MenuItem, react-router NavLink was changed to BEAM NavLink

src/components/Pagination.stories.tsx, src/components/Pagination.test.tsx, src/components/Pagination.tsx
Most of my hackday was BE paging, but this changes some of the FE, specifically:
* Combines the previous `settings` and `setSettings` props into a single `page` tuple
* Supports both `pageNumber`+`pageSize` as well as `offset`+`limit`, based on caller pref
* Defaults to `offset`+`limit` since that is what our BE filters want
* Reduces # of page size options, plus makes each increment larger/further away from each other
* Removes the `label` prop as unnecessary
* Fixes some boundary cases in the "x - y of z" on the last page of data / only a single page of data
=> refactor: Refactor Pagination component

src/components/SuperDrawer/SuperDrawer.stories.tsx, src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/TableStyles.tsx, src/components/Table/components/Row.tsx, src/components/Table/components/cell.tsx, src/components/Table/types.ts, src/components/Table/utils/utils.tsx
Default and 'condensed' table styles now use the latest patterns.
Includes some various simplifications
=> feat: Replace GridTable default styling

src/components/Chip.stories.tsx, src/components/Chip.test.tsx, src/components/Chip.tsx, src/components/Chips.stories.tsx, src/components/Chips.test.tsx, src/components/Chips.tsx
[SC-35341](https://app.shortcut.com/homebound-team/story/35341/beam-chips-grouped-and-chip-style-improvements)
1. Add "color" | "backgroundColor" to Chip (singular) XSS
2. Add compact prop to change Chips (group) size
3. New "info" type to ChipTypes
=> feat: Chips/Chip xss and compact prop

src/inputs/MultiSelectField.tsx, src/inputs/SelectField.tsx, src/inputs/internal/ComboBoxBase.tsx
Also sneaks in a simplification of MultiSelectField.onSelect.
=> docs: Expand comments for unsetLabel and nothingSelectedText.

package.json, src/components/ButtonGroup.test.tsx, src/components/ButtonGroup.tsx
The text on this already gets rendered as a ReactNode `<button>{text}</button>`, but the Typing is only allowing Strings through. So let _me_ use what _Beam_ is already doing. 
Specifically, I need to be able to make `Reject` Red:
Previously I needed to color the icons (#874)
Both of these would've been solvable if the Type was being exposed in the same way it's being used.
=> feat(button-group): allow JSX

src/components/Accordion.tsx, src/components/AccordionList.stories.tsx
* Adds optional `xss` prop in order to have control over changing the padding on the blueprint side
=> feat: SC: 35536 - Add optional xss for padding on accordion

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/utils/TableState.ts
I need to that `initSelected` on rows works on children
https://60466f7d43c37c0021788867-xuabsrkbed.chromatic.com/?path=/story/components-table-gridtable--selectable-children-rows
=> feat: add the functionality of the initSelected of children rows on init load

src/hooks/index.ts, src/hooks/useFilter.test.tsx, src/hooks/useFilter.ts
There are times we do _not_ want a filter to be persisted. 
This PR adds a hook to work with Beam's filters to that does not persist the filter values in query params or browser storage
=> feat: Add useFilter hook for non-persisted filters

src/components/Table/GridTable.test.tsx, src/components/Table/GridTableApi.ts, src/components/Table/Table.qa.stories.tsx, src/components/Table/utils/TableState.ts
When introducing the 'TableState.keptSelectedRows' we assumed that the reason for a row being removed was due to filters. However, it is possible for a row to be removed intentionally due to deleting it. Adding a 'GridTableApi.deleteRows' method to ensure we do not keep these rows around in the 'keptSelectedRows' and actually delete them.
=> feat: Add TableState.deleteRows

src/components/internal/DatePicker/DatePickerOverlay.tsx, src/forms/BoundDateField.test.tsx, src/forms/BoundDateRangeField.test.tsx, src/inputs/DateFields/DateField.test.tsx, src/inputs/DateFields/DateFieldBase.test.tsx, src/inputs/DateFields/DateFieldBase.tsx, src/inputs/DateFields/DateRangeField.test.tsx, src/inputs/TextFieldBase.tsx
Fixes issue where the DatePicker was often rendering underneath the virtual keyboard, preventing users from using the DatePicker. To fix this, DateFieldBase now identifies if it is being used on a touch device. If it is, then it sets the new `TextFieldBase.preventEdit` property to set the input as "readonly". This forces touch screen users to only use the DatePicker for changing dates.
Additional changes include:
- Move focus to the DatePicker once it is opened and return focus to input when DatePicker is closed.
Updates tests based on new logic for moving focus around
=> fix: SC-37802 Prevent DatePicker triggering virtual keyboard on touch devices

src/forms/BoundRadioGroupField.test.tsx, src/inputs/NumberField.test.tsx, src/inputs/NumberField.tsx, src/inputs/TextAreaField.test.tsx
This makes it more consisent with the "+$0" we show for read-only diffs, and highlights "this field is a diff" in UIs where the "+" is the only indication that this is a diff field.
I.e. to make this table of inline edit fields more consistent:
=> feat: Show plus zero when displayDirection is set.

src/components/AutoSaveStatus/AutoSaveStatusProvider.tsx, src/components/AutoSaveStatus/index.ts, src/components/AutoSaveStatus/useAutoSaveStatus.test.tsx, src/components/AutoSaveStatus/useAutoSaveStatus.ts, src/components/BeamContext.tsx, src/components/index.ts
It originally existed in form-state b/c we used form-state internals to trigger the auto-saving yes/no behavior.
But since then we've moved the "trigger auto-saving yes/no" to the GraphQL mutation instrumentation in apolloHooks, b/c then all pages got the auto-save behavior and not just those using form state.
So, moving it here so we can remove from form-state.
=> feat: Move AutoSaveStatus into beam.

src/components/Table/GridTable.test.tsx, src/components/Table/utils/RowState.ts
Fixes an assumption some Invoicing v2/expense tables were making, of deriving children like `row.children = someOtherList.map(...)`, and if `someOtherList` was empty, they want the row to be selectable / i.e. not really a parent.
=> fix: Allow selecting parents with no children.

src/components/Table/GridTable.tsx, src/components/Table/utils/TableState.ts, src/setupTests.tsx
This doesn't really change any behavior/fix any bugs, it is just more kosher/avoids the React warning.
=> fix: Call setMatchedRows from useEffect

src/components/Filters/DateRangeFilter.test.tsx, src/forms/BoundDateField.test.tsx, src/forms/BoundDateRangeField.test.tsx, src/inputs/DateFields/DateField.test.tsx, src/inputs/DateFields/DateFieldBase.test.tsx, src/inputs/DateFields/DateFieldBase.tsx, src/inputs/DateFields/DateRangeField.test.tsx
The DatePicker now opens when the input is clicked instead of when it is focused. This is to prevent the DatePicker from re-opening when focus is returned to the field after selecting a date.
We were managing a variable to know whether or not the focus was returned to the input due to the DatePicker closing. However, there were some race conditions introduced when using multiple FocusScope components. Specifically, when the DateField’s `onChange` method triggers a modal, then we were attempting to return focus to the input field, and at the same time move focus to modal. React-Aria uses a requestAnimationFrame to restoreFocus, which was causing the race condition between when the focus moves and when it gets restored. By removing the behavior of focus triggering the DatePicker, then we …
=> fix: DatePicker to open via click instead of focus

src/components/Table/GridTable.test.tsx, src/components/Table/utils/RowState.ts, src/components/Table/utils/RowStates.ts, src/components/Table/utils/TableState.ts
This means the `setRows` really only runs when rows actually change, hence MobX no longer upgrades the rows array to an ObservableArray behind the scenes.
=> feat: Use observerable.ref for rows as well.

src/components/Accordion.stories.tsx, src/components/Accordion.tsx, src/components/AccordionList.stories.tsx, src/components/AccordionList.tsx
Adds 'compact' variant to the Accordion and AccordionList components. When defining 'compact' it will modify the default typography, padding, icon size and background color of the accordion header.
=> feat: SC-38355 - Accordion compact variant

src/components/Table/GridTable.tsx, src/components/Table/Table.qa.stories.tsx
This was a pre-GridTableApi callback that also isn't used in internal-frontend anymore.
=> feat: Remove unused setRowCount.

src/hooks/useComputed.ts
Otherwise if a useComputed returns something cyclic like ReactElements, we'll get infinite loops errors.
=> fix: Use shallow equality in useComputed.

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/GridTableApi.ts, src/components/Table/components/Row.tsx, src/components/Table/hooks/useSetupColumnSizes.ts, src/components/Table/types.ts, src/components/Table/utils/ColumnState.ts, src/components/Table/utils/ColumnStates.ts, src/components/Table/utils/ColumnStorage.ts, src/components/Table/utils/GridRowLookup.ts, src/components/Table/utils/RowState.ts, src/components/Table/utils/RowStates.ts, src/components/Table/utils/RowStorage.ts, src/components/Table/utils/TableState.ts, src/components/Table/utils/columns.tsx, src/components/Table/utils/utils.tsx
Add a `GridRowApi` that is the same as `GridTableApi` but adds a per-row `visibleChildren` that cells can use to calc things like sums/totals.
I ended up refactoring a lot of the GridRowProps ... I kinda forget why/if I really needed to, but had been meaning to do it for awhile.
=> feat: Add Row Api with visibleChildren, selectedChildren

src/components/Table/GridTableApi.ts
To move LotSequencePage off of RowLookup, which since it's a ref, is not being set in a test due to the useEffect-ification of GridTable.
=> feat: Add GridTableApi.getVisibleRows.

src/utils/rtl.tsx
Something in my React 18 branch doesn't like the `#` selector we make:
```
SyntaxError: '#react-aria2127286360-:r5m:' is not a valid selector
at emit (/home/circleci/project/node_modules/nwsapi/src/nwsapi.js:557:17)
at _querySelectorAll (/home/circleci/project/node_modules/nwsapi/src/nwsapi.js:1494:9)
at Object._querySelector [as first] (/home/circleci/project/node_modules/nwsapi/src/nwsapi.js:1405:14)
at HTMLBodyElementImpl.querySelector (/home/circleci/project/node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:69:44)
at HTMLBodyElement.querySelector (/home/circleci/project/node_modules/jsdom/lib/jsdom/living/generated/Element.js:1094:58)
at selectOption (/home/circleci/project/node_modules/@homebound/beam/dist/utils/rtl.js:173:26)
at …
```
=> fix: Use getElementById to find the listbox.

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx, src/components/Table/types.ts
* Adds a new `nextPageLoading` option to `GridTable` `infiniteScroll` prop that will show a loading spinner in the footer when provided the `query.loading` boolean. In an ideal world, the scroll would truly be "infinite" AKA we fetch the next page before a user reaches the end, but a slow connection or very fast scroll could leave an awkward gap where it's unclear if you've reached the true end or are just waiting for the next page. 
* Demo Story: https://60466f7d43c37c0021788867-ivzonzyhpo.chromatic.com/?path=/story/components-table-gridtable--infinite-scroll-with-loader
https://www.loom.com/share/9d6a9dd24ee74b8f9001e1a6dda91a6e?sid=e13b2cc3-ffc0-4294-aed0-2e9bae5c9853
=> feat: Add loading spinner option to infinite scroll

src/hooks/useComputed.ts, src/utils/defaultTestId.test.ts, src/utils/defaultTestId.ts
Going to wait to merge this after the bump-react PRs land to avoid conflicts.
=> fix: Strip colons from default test ids.

src/components/Table/GridTable.test.tsx, src/components/Table/components/Row.tsx, src/components/Table/utils/RowState.ts
We have a use case that requires parent rows to be selectable independently of their children, so we should allow that to happen with a simple flag.
This behavior is not handled by the inferSelectedState flag.
[SC-39801](https://app.shortcut.com/homebound-team/story/39801/selecting-add-row-always-selects-and-won-t-let-you-deselect-modify-rows)
=> feat: [SC-39801] allow independent parent select for GridTable rows

package.json, yarn.lock
The previous release forced applications to get mobx-react 9.x
=> fix: Bump form-state w/mobx as a peer dependency.

src/components/Grid/ResponsiveGrid.stories.tsx, src/components/Label.tsx, src/inputs/SelectField.stories.tsx, src/inputs/TextAreaField.tsx, src/inputs/TextFieldBase.tsx, src/inputs/hooks/useGrowingTextField.tsx, src/inputs/internal/ComboBoxBase.tsx, src/inputs/internal/ComboBoxInput.tsx
SelectField and MultiSelectField will now support multiline inputs either via `multiline` prop being set to true, or whenever the `PresentationProvider.wrap` prop is set to `true`. E.g. When GridTable is rendered with `rowHeight: "flexible"` (default) then the SelectFields will support wrapping text.
=> feat: Support multiline inputs for select fields

src/components/Filters/SingleFilter.tsx, src/inputs/SelectField.stories.tsx, src/inputs/SelectField.test.tsx, src/inputs/SelectField.tsx, src/inputs/TreeSelectField/TreeSelectField.stories.tsx, src/inputs/TreeSelectField/TreeSelectField.test.tsx, src/inputs/TreeSelectField/TreeSelectField.tsx, src/inputs/TreeSelectField/utils.ts, src/inputs/internal/ComboBoxBase.tsx
I.e. if a variable in the GQL query changed, after we've done the initial load.
=> feat: Allow lazy-loaded SelectFields to change their options.

src/components/Table/GridTable.test.tsx, src/utils/rtl.tsx
So we can assert against only a subset of columns, and have less noisy assertions especially for tables like Specs & Selections with ~lots of columns.
=> feat: Add column names to tableSnapshot.

src/forms/BoundIconCardGroupField.test.tsx, src/forms/BoundIconCardGroupField.tsx, src/inputs/IconCardGroup.stories.tsx, src/inputs/IconCardGroup.tsx
This is a fix to be able to use the IconCardGroup with enum values
=> fix: IconCardGroup generic typing

package.json, src/Css.ts, src/components/Pagination.stories.tsx, src/components/PresentationContext.tsx, src/forms/FormLines.stories.tsx, src/forms/FormLines.tsx, src/inputs/Autocomplete.stories.tsx, src/inputs/Autocomplete.tsx, src/inputs/DateFields/DateField.stories.tsx, src/inputs/DateFields/DateFieldBase.tsx, src/inputs/DateFields/DateRangeField.stories.tsx, src/inputs/MultiSelectField.stories.tsx, src/inputs/NumberField.stories.tsx, src/inputs/NumberField.tsx, src/inputs/RichTextField.tsx, src/inputs/SelectField.stories.tsx, src/inputs/TextAreaField.stories.tsx, src/inputs/TextField.stories.tsx, src/inputs/TextFieldBase.tsx, src/inputs/TreeSelectField/TreeSelectField.stories.tsx, src/inputs/TreeSelectField/TreeSelectField.tsx, src/inputs/internal/ComboBoxBase.tsx, src/inputs/internal/ComboBoxInput.tsx, src/inputs/utils.ts, yarn.lock
Adds support for a `PresentationFieldProps.fullWidth` property. The following components will respect the property:
- FormLines
- TextField
- TextAreaField
- RichTextField
- SelectField
- MultiSelectField
- DateField
- NumberField
- TreeSelectField
Updates the `FormLines` component to default to the `"lg"` size instead of `"full"`. This will hopefully minimize the impact on existing layouts as the previous default width for each field within `FormLines` was 550px. By using the `lg` size, we'll continue to default the fields within `FormLines` to 550px.
=> feat: Support 'fullWidth' prop on all text fields

src/components/Label.tsx, src/inputs/Switch.stories.tsx, src/inputs/Switch.tsx
Adds new 'labelStyle: "centered"'. This will stack the label on top of the switch and center both elements in the column. Updates how tooltips are rendered for Switches. Now includes an icon to denote there is a tooltip, rather than requiring the user to discover it by hovering over it.
Adds this tooltip functionality to the Label component, though it is only currently used by Switch. At some point it would be good to move all Tooltips to this sort of UX.
=> feat: Update Switch component styling

src/inputs/TreeSelectField/TreeSelectField.stories.tsx, src/inputs/TreeSelectField/TreeSelectField.tsx, src/inputs/internal/ComboBoxBase.tsx
This PR fixes `TreeSelectField` and `MultiSelectField` read-only renders.
=> fix: multiselect read-only

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx, src/components/Table/components/Row.tsx, src/components/Table/utils/RowStates.ts, src/components/Table/utils/columns.tsx, src/components/Table/utils/utils.tsx
Card style rows don't work with padding as spacing, and we can't use margin and still get drop events. So we need a containing element for padding and drag & drop events.
=> feat: Drag & Drop fast follow for card style rows

src/components/Filters/TreeFilter.test.tsx, src/inputs/TreeSelectField/TreeSelectField.tsx
[SC-44850](https://app.shortcut.com/homebound-team/story/44850/bug-bash-row-height-expands-too-much-when-adding-alot-of-scope)
* Previously if you selected a parent in the tree select and clicked inside of the input, the selection would stick and you could not select another option. 
* This fix allows us to persist the selected option (filter) and show other options for users to select.
BUG Video: https://www.loom.com/share/3a420d77f70e4470a18e3f598984e5cb
Fix Video: https://www.loom.com/share/d8155d01a0764cf9816c4249302ada1e
=> fix: Update tree select field state

src/forms/BoundSelectField.test.tsx, src/forms/BoundSelectField.tsx, src/forms/formStateDomain.ts, src/inputs/SelectField.test.tsx, src/inputs/SelectField.tsx, src/inputs/Value.ts, src/types.ts, src/utils/index.ts, src/utils/options.ts
`getOptionValue` is now optional for `options` with ids or codes.
`getOptionLabel` is now optional for `options` with name, displayName, or labels.
=> feat: Add more overloads for SelectField options.

src/inputs/TreeSelectField/TreeSelectField.tsx, src/inputs/internal/ComboBoxBase.tsx
https://www.loom.com/share/27ec8874b4f549b2813dd8563ea7b68f?sid=d55983ea-d3f2-4679-a658-03a3fc9cbffd
=> fix: Clear search terms and reset dropdown options when dropdowns re-open

src/components/internal/DatePicker/DatePicker.stories.tsx, src/components/internal/DatePicker/DatePicker.tsx, src/components/internal/DatePicker/DateRangePicker.stories.tsx, src/inputs/DateFields/DateFieldBase.tsx
Adds the year selection header as an option to SingleDateFields. This is the same component the RangeDateField uses.
[SC-47338](https://app.shortcut.com/homebound-team/story/47338/enable-type-to-edit-and-search-by-year-month-for-mls-list-date-field-on-subject-page)
=> feat: add year selection header option to DatePicker;

src/components/Modal/Modal.tsx
Use `height: 100dvh` (dynamic viewport height) vs `100vh` as it takes into account the address bar and other "chrome" added around the viewport. This results in a better output for the screen. 
`dvh` and `dvw` has been supported in iOS, and most browsers since early-mid 2022. More specifically as of iOS/Safari v15.4, Chrome v108, Firefox v101. See MDN docs for a more complete [browser support](https://developer.mozilla.org/en-US/docs/Web/CSS/length#browser_compatibility).
| **100vh** | **100dvh** |
|-----------| -----------|
| ![Simulator Screenshot - iPhone 15 - 2024-04-22 at 10 06 25](https://github.com/homebound-team/beam/assets/1143861/4636e053-cdef-4302-aa6a-31b66c967771) | ![Simulator Screenshot - iPhone 15 - 2024-04-22 at 10 07 …
=> fix: Use dvh/dvw instead of vh/vw for mobile

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.tsx, src/components/Table/utils/utils.tsx
For virtualized tables we subtract 20px from the total width to account for a vertical scrollbar, which helps prevent horizontal scrollbars. The fallback message was not respecting that adjusted width.
| Before | After |
| --- | --- | 
| <img width="536" alt="Screenshot 2024-05-10 at 4 16 32 PM" src="https://github.com/homebound-team/beam/assets/1143861/e70eec55-78e2-4672-9141-49823b2b9ccb"> | <img width="499" alt="Screenshot 2024-05-10 at 4 16 47 PM" src="https://github.com/homebound-team/beam/assets/1143861/e9f7ab88-cbfd-4065-99dd-1ad91b7df9c0"> |
=> fix: Fallback message for virtual table was exceeding table header width

src/components/Label.tsx, src/inputs/TextFieldBase.tsx, src/inputs/ToggleChipGroup.tsx
Kind of an annoying issue that I've see is you try to click away from a SelectField to close the menu, but instead the menu flickers and opens back up. This was due to clicking above the field, which happened to be still clicking on the label element which was taking up the full width of its container. When clicking a label element, then the focus is set to the associated field. By adding 'align-self: flex-start', then the label element no longer extends the full width of the container.
See Loom for example:
https://www.loom.com/share/7b2dd9d22c1a457f991aca884a45731b
=> fix: Form Labels to not extend full width of field

src/Css.ts, src/components/Pagination.tsx, src/inputs/MultiSelectField.test.tsx, src/inputs/TextFieldBase.test.tsx, src/inputs/TextFieldBase.tsx, src/inputs/internal/ComboBoxInput.tsx, truss-config.ts
All multiselect fields will show selected options within the field. Tab functionality is preserved. It's not a full rework like what's laid out in [this old Figma](https://www.figma.com/design/GEXYjIEDKFRjoFbnrt515r/New-Multiselect-Component-%E2%9C%A8?node-id=5-14&t=QHpFO2gb9HhNE2yB-0) but should make some people happy.
https://github.com/homebound-team/beam/assets/108819408/a4ac3709-630c-4834-863d-e6b3e13c9b1f
- This also adds a list tooltip to the selected count.
- ![Screenshot 2024-05-17 at 3 01 33 PM](https://github.com/homebound-team/beam/assets/108819408/2e5f756a-5b6b-47f8-9091-89af3229dfc1)
Couple spots I could use some design help
- 
- I set the placeholder container width to `100%` to fill the space. It does introduce some weirdness when fields extend far. How should we handle …
=> feat: hackday multiselect shows selected options in field

src/components/Pagination.tsx, src/inputs/internal/ComboBoxInput.tsx
- Fixes single selects using chips. I missed a check for `isMultiSelect`
- Reverts pagination to original size
=> fix: ComboBoxInput.tsx uses chips only if multiselect

src/components/Accordion.stories.tsx, src/components/Accordion.test.tsx, src/components/Accordion.tsx
In DesignPackage, we want to be able to select "All these slots" by clicking on a header, like so:
This PR adds an optional `titleOnClick` function that, when provided, slightly alter the behavior of the Accordion:
1. Clicking the title no longer performs expand/collapse
- We still want whitespace between the icon and title to be clickable, so it has to `fg0` instead of the span's `fg1`
- Stop propagation so w don't trigger expand's onClick
=> feat(accordion): clickable title

src/components/Filters/TreeFilter.test.tsx, src/inputs/TreeSelectField/TreeSelectField.stories.tsx, src/inputs/TreeSelectField/TreeSelectField.test.tsx, src/inputs/TreeSelectField/TreeSelectField.tsx, src/inputs/TreeSelectField/utils.ts
Improvements includes:
- Configurable 'chipDisplay' to only show the leaf, root, or all options in the field and tooltip.
- Supports disabled leaf nodes.
- Dedupes selections if there are multiple of the same option within different trees
- Respects changes to 'values' prop
=> fix: TreeSelectField improvements

src/Css.ts, truss-config.ts
Per Dave, the current overlay is too faint.
=> fix: Bump overlay opacity to 0.6.

src/components/Table/TableStyles.tsx, src/components/Table/components/Row.tsx
=> feat: Adding support for multiple levels of nesting on grid tables, to keep adding marging based on the level of nesting index

src/components/Tag.test.tsx, src/components/Tag.tsx, src/components/Tooltip.tsx
Tag updates:
- 'text' property is now of type ReactNode.
- Conditionally adds tooltip if content overflows
- Can force prevent tooltip from rendering. For cases where you're already wrapping the Tag in a Tooltip to display additional info.
Tooltip updates:
- Support a background color
- Add box-shadow styles
=> feat: Update Tag and Tooltip support

src/components/Filters/MultiFilter.tsx, src/components/PresentationContext.tsx, src/forms/FormLines.stories.tsx, src/forms/FormLines.tsx, src/inputs/Switch.stories.tsx, src/inputs/Switch.tsx, src/inputs/TextFieldBase.tsx, src/inputs/ToggleChipGroup.tsx
Add support for changing the width allocated between the label and form field when using labelStyle="left" via a 'labelLeftFieldWidth' property on the PresentationContext.FieldProps.
Updates stories to showcase new changes and features
=> feat: Support labelStyle in ToggleChipGroup

src/components/Filters/DateRangeFilter.tsx
It had been using React.Key, which is similar-ish to Value, but in newer Reacts starts including `bigint` which our Value doesn't support yet.
...and actually instead of `V` / `Value`, this op is really just modeling the `op: between | before | after | etc` type union, so doesn't need to be anything more than `extends string` afaict.
=> fix: Fix dateRangeFilter generic to extend string.

src/components/ButtonMenu.tsx, src/components/internal/Menu.stories.tsx, src/components/internal/MenuItem.tsx
[SC-54926](https://app.shortcut.com/homebound-team/story/54926/update-libraries-menu)
* Updating our `Libraries` Nav - Menu Item to include `dividers` for specific sections, so updating `MenuItem` to include an optional `hasDivider` prop to render divider lines
* Cannot use `PersistentItems` as that only handles showing one persistent item
=> feat: add divider to menu item

src/components/Chip.stories.tsx, src/components/Chip.tsx, src/inputs/ToggleChipGroup.stories.tsx, src/inputs/ToggleChipGroup.tsx
=> feat: Adding start adornment to Chips

src/inputs/ToggleChipGroup.tsx
remove wrapper div from toggle chip group so our test can get the option by text
=> fix: remove wrapper div from toggle chip group so our test can get the options by text

src/components/Filters/Filters.stories.tsx, src/inputs/TreeSelectField/TreeSelectField.test.tsx, src/inputs/TreeSelectField/TreeSelectField.tsx, src/inputs/TreeSelectField/utils.ts, src/inputs/internal/ComboBoxBase.tsx
Updates/fixes include:
1. TreeSelectField can reset values when outside component sets values to undefined
2. Can set individual groups to be default collapsed
3. Increase min-width of ListBox from 200 to 320px wide per Design feedback
=> fix: TreeSelectField and treeFilter fixes

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/GridTableApi.ts, src/components/Table/components/Row.tsx, src/components/Table/components/cell.tsx, src/components/Table/types.ts, src/components/Table/utils/utils.tsx
As easy as:
```
const api = useGridTableApi();
<Button onClick={() => api.downloadToCsv("report.csv")} label="CSV" />
```
Currently assumes all of the data is already available client-side -- not really sure how this would work with server-side driven pagination.
Also assumes we want all of the columns/rows included, and that they're directly mapped from the `content` / `value` keys. We could also add a `csvValue` to let columns provide CSV-specific values.
=> feat: Add GridTable csv export.

src/components/Table/GridTable.test.tsx, src/components/Table/GridTable.tsx, src/components/Table/GridTableApi.ts, src/components/Table/utils/TableState.ts
To add csv-specific rows to an export/copy.
=> feat: Add GridTable.csvPrefixRows.

src/inputs/internal/VirtualizedOptions.tsx
React 18.3 detects `key` being spread and doesn't like it.
=> fix: Avoid 'key prop spread into JSX' warning.

src/utils/rtl.tsx
When the SelectField is read only.
=> fix: Give select a more useful error message.

src/inputs/hooks/useGrowingTextField.stories.tsx, src/inputs/hooks/useGrowingTextField.tsx
Issue: when rendering a SelectField in a GridTable with no nested rows the select renders with the correct height, when updating the table to have nested rows the select field will fail calculating the new correct height, this change adds another delayed called that gives a better chance of having enough time for GridTable finishing the rendering so that `useGrowingTextField` will get the correct value.
=> fix: SC-59775 fix nested select height after long render

src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.tsx, src/components/Modal/TestModalContent.tsx
Orchestration has been asked to combine the dynamic schedule draft mode with the standard view. The draft pages were built as individual routes using a shared store to pass task changes between them. In combining these pages, we need to warn users their changes will be lost before allowing them to navigate away. Since we're using a shared store and not just a shared form I want to update Blueprints `<NavigationContext />` `navigationCheckCallbacks` to support more robust nav checks. I've gotten that working, but since the inner `<NavigationPrompt />` from `react-router-navigation-prompt` passes its own callback when a cancel action happens, routing breaks if a user clicks outside of our modal or closes with the `x` icon since the NavigationPrompt inner onCancel callback is never called. …
=> feat: add modal prop to force modal interaction;

src/components/internal/OverlayTrigger.tsx
I've had to write this
```
<ButtonMenu
// @ts-ignore: it works but prop isn't exposed
trigger={{ icon: "verticalDots", inc: 2.3 }}
```
more than a few times lately 😄
=> fix: expose `inc` prop on OverlayTriggerProps

src/components/Table/GridTableApi.ts, src/components/Table/types.ts
Title
Found we needed an update in https://github.com/homebound-team/internal-frontend/pull/6048
=> fix: gridtable smooth scroll default; expose options;

src/inputs/TreeSelectField/TreeSelectField.test.tsx, src/inputs/TreeSelectField/TreeSelectField.tsx
Allows to filter options on a tree select field even if the parent option is collapsed.
=> fix: allow searching in collapsed TreeSelectField

src/components/PresentationContext.tsx, src/inputs/SelectField.stories.tsx, src/inputs/TextFieldBase.tsx, src/inputs/internal/ComboBoxBase.tsx
[SC-61998](https://app.shortcut.com/homebound-team/story/61998/houston-pilot-feedback-update-beam-to-support-coloring-dropdowns) | [Figma](https://www.figma.com/design/xQ3iNLHJCFEJeOi7boONY4/Q1-Q4-2024-%7C-Dynamic-Schedules?node-id=11535-84519&node-type=frame&t=wrjRlakQknbMmW1j-0)
https://github.com/user-attachments/assets/61fdf544-1949-475c-b01d-f805504a7f61
Initially the goal was to only have select fields show color but since the underlying `<TextFieldBase` that actually controls colors takes props from presentationFieldProps it was pretty easy to hook up the components starting from there. So technically our `<MultiselectField also supports `getInputStylePalette` & `inputStylePalette` and our `<TextFields` support `inputStylePalette` as well practically for free.
=> feat: palette fill as a presentation prop; getInputStylePalette fn prop;

src/components/Table/GridTable.test.tsx, src/components/Table/GridTableApi.ts
Story details: https://app.shortcut.com/homebound-team/story/63506
=> feat: [sc-63506] Flip -s to 0s in the interest summary export

src/components/Table/GridTable.tsx, src/components/Table/GridTableApi.ts, src/components/Table/index.ts, src/components/Table/types.ts, src/components/Table/utils/GridRowLookup.ts
* Example use case on the schedule where the `scrollIntoView` is helpful when moving a task to a date that is outside of the current viewport, but we don't want it to move if it's still visible after a given change. https://www.loom.com/share/a58929dc5354403f855628e60212c1e5
* This somewhat hand-rolled implementation is due to virutoso not exposing this option, some context on this thread where the preferred option is to use an intersection observer, but that seems like overkill given there may be 50+ rows rendered on a large screen https://github.com/petyosi/react-virtuoso/issues/118
=> feat: [Sc-63907] Skip scrollToIndex if row is already in view

src/components/Filters/MultiFilter.stories.tsx, src/components/Filters/MultiFilter.test.tsx, src/components/Filters/testDomain.ts, src/inputs/internal/ComboBoxBase.tsx
A bug was reported on the `ChangeLog` page, where the project filter search was not working
[SC-64282](https://app.shortcut.com/homebound-team/story/64282/projects-filter-not-working-properly-on-change-log)
When I added back in the `debouncedSearch` early return, the project filter was fixed, but it caused a bug with the regular select field per the slack threads below and PRs
* Slack Thread: https://homeboundinc.slack.com/archives/G01QEA5CXL1/p1734450733938479 
* PRs:
* https://github.com/homebound-team/beam/pull/1017/files#diff-4cfc44d3175cb7b1fc2f316109423cede94d022b834134087a6a15bdbe4f296eL280
* https://github.com/homebound-team/beam/pull/1098/files
I still think this needs an early return, so I changed it to look at the `onSearch` prop and do an early return from that check.
I tested …
=> fix: SC-64282: Add back in early return for onSearch/debounce

src/components/Table/GridTable.stories.tsx, src/components/Table/GridTable.test.tsx, src/components/Table/utils/RowState.ts
We've encountered an issue where users cannot select or deselect all rows when a table contains only un-selectable rows, whether grouped or not. For example, if a table includes a header row, a group row, and a single un-selectable child row, selecting all leaves the group unselected and the header in an indeterminate state. This fix ensures that the header and/or groups are marked as `checked` even when only un-selectable rows are present.
https://www.loom.com/share/a6473aa3fce044e698f00201ed5c5348
=> fix: Handle "Select All" when only unselectable child rows are present

src/components/AccordionList.stories.tsx, src/components/AccordionList.tsx, src/components/Avatar/AvatarButton.stories.tsx, src/components/Icon.stories.tsx, src/components/Icon.tsx, src/components/IconButton.stories.tsx, src/components/SuperDrawer/SuperDrawer.tsx, src/components/Table/components/Row.tsx, src/components/ToggleChip.tsx, src/foundations/BoxShadow.stories.tsx, src/foundations/Color.stories.tsx, src/foundations/Typography.stories.tsx, src/inputs/CheckboxBase.tsx, src/inputs/Examples.stories.tsx, src/inputs/IconCard.stories.tsx, src/inputs/Switch.stories.tsx, src/inputs/ToggleButton.stories.tsx
I'm prototyping a CSS runtime, Fela, that wants `&` at the start of selectors; emotion supports that as well, so just move to that.
=> chore: Simplify selectors.

src/forms/BoundSelectField.test.tsx, src/forms/labelUtils.ts, src/inputs/SelectField.stories.tsx, src/inputs/TextFieldBase.tsx
Fixes usages like:
Which admittedly should probably be using StaticFields.
=> fix: Don't show asterisk when readonly.

src/forms/BoundCheckboxGroupField.tsx, src/forms/BoundToggleChipGroupField.tsx, src/forms/FormStateApp.tsx, src/forms/SubmitButton.test.tsx, src/forms/SubmitButton.tsx, src/inputs/CheckboxGroup.tsx, src/inputs/ToggleChipGroup.tsx
When duplicating an entity, we might have a form that is valid but also not dirty, b/c technically the user hasn't touched anything yet, but we've prefilled existing values, and still want want to allowing hitting Save.
=> fix: Enable SubmitButton on new entities.

src/components/NavLink.test.tsx, src/components/NavLink.tsx
This will enable the use of custom styling (e.g. padding) within the label, providing flexibility needed for the upcoming `SideNav` redesign.
=> feat: Add ReactNode support for NavLink labels

src/components/Layout/FormPageLayout.test.tsx, src/components/Layout/FormPageLayout.tsx, src/forms/BoundForm.stories.tsx, src/forms/BoundForm.tsx, src/forms/SubmitButton.tsx, src/inputs/Checkbox.stories.tsx, src/inputs/Checkbox.tsx, src/inputs/CheckboxBase.tsx
A couple of small changes I noticed while implementing a `FormPageLayout`
* Addresses feedback on making the `submitAction` prop required from here: https://github.com/homebound-team/beam/pull/1123#discussion_r2024891966
* Fixes a type issue where the mapped type for `reactNode*` keys were not made optional if an input type for the form was required
* Also allows the checkbox to show a disabled tooltip
* Swaps out the normal submit action button with `SubmitButton` for the new standard disabled state behavior.
=> feat: Updates to `FormPageLayout` and `BoundForm`

src/components/Accordion.test.tsx, src/components/Accordion.tsx
While `titleOnClick` does something similar, we also need a way to run logic when the accordion is expanded/collapsed without modifying the title or `RotatingChevronIcon` behavior.
=> feat(accordion): add onToggle

.vscode/settings.json, src/components/ScrollShadows.tsx
The idea behind this fix is to use data-chromatic="ignore", as defined in https://www.chromatic.com/docs/ignoring-elements/. I'm thinking it'd be better to always have these elements present to be ignored. Not sure if even with the ignore attribute, having the shadow elements sometimes render and sometimes not would cause the same inconsistencies (which is the current issue).
=> fix: Attempting to fix ScrollShadow chromatic snapshots

src/forms/BoundForm.stories.tsx, src/forms/BoundForm.test.tsx, src/forms/BoundForm.tsx, src/forms/BoundListField.tsx, src/forms/formStateDomain.ts
Provides a standardized way to implement a "list" type filed from `form-state` within the new `BoundForm` layout
Example config:
```ts
{
listFieldBooks: {
name: "Book",
rows: [{ title: boundTextField() }, { isPublished: boundSwitchField() }],
onNew: (objectState) => {
objectState.add({ title: undefined, isPublished: false });
},
onDelete: (listFieldState, rowObjectState) => {
if (rowObjectState.id.value) {
rowObjectState.set({ delete: true });
} else {
listFieldState.remove(rowObjectState.value);
}
},
filterDeleted: (objectState) => !objectState.delete?.value,
}
```
=> feat: [SC-68648] Bound Form List Field Support

src/components/Chip.tsx, src/components/Chips.test.tsx, src/components/ToggleChip.stories.tsx, src/components/ToggleChip.test.tsx, src/components/ToggleChip.tsx, src/inputs/ChipSelectField.tsx, src/inputs/ChipTextField.stories.tsx, src/inputs/ChipTextField.test.tsx, src/inputs/ChipTextField.tsx, src/inputs/internal/ListBoxChip.tsx
* Adds shared base styles for the Chip and ToggleChip components
* Uses some lighter background colors
* Adds an optional icon on the left of the text
* Makes the x icon background match the rest of the chip 
* Updates bg colors and X icon color
=> feat: Update Chip components

src/components/Layout/GridTableLayout/GridTableLayout.stories.tsx, src/components/Layout/GridTableLayout/GridTableLayout.test.tsx, src/components/Layout/GridTableLayout/GridTableLayout.tsx, src/components/Layout/GridTableLayout/QueryTable.tsx, src/components/Layout/Layout.stories.tsx, src/components/Layout/index.ts, src/hooks/usePersistedFilter.ts
A layout component that combines a table with a header, actions buttons and filters. Story for this branch: https://sc-68262-table-page-layout--60466f7d43c37c0021788867.chromatic.com/?path=/story/components-layout-gridtablelayout--query-table-layout
This component can render either a `GridTable` or wrapped `QueryTable` based on the provided props:
- For static data or custom handled loading states, use `rows` to pass in the data directly:
```tsx
<GridTableLayout
tableProps={{
rows: [...],
columns: [...],
}}
/>
```
- To take advantage of data/loading/error states directly from an Apollo query, use `query` and `createRows`:
```tsx
<GridTableLayout
tableProps={{
query,
createRows: (data) => [...],
columns: [...],
}}
/>
```
- For filtering, search and group by, this component is also intended …
=> feat: [SC-68262] Grid table layout

src/components/Layout/FormPageLayout.stories.tsx, src/components/Layout/FormPageLayout.tsx, src/components/Snackbar/Snackbar.tsx
`FormPageLayout` is displayed as a full-screen modal, which prevents notifications from being visible during user actions (via `Snackbar`) or query errors (via `BannerNotice`). We need to add support for both types of notifications.
=> feat: [SC-70480] Enable Banner/Snackbar in FormPageLayout

src/components/IconButton.stories.tsx, src/components/IconButton.test.tsx, src/components/IconButton.tsx
Instead of a manual Tooltip wrapper:
```
<Tooltip title={`Download ${trade.tradePartner.name} bid`} placement="top">
<IconButton icon="download" onClick={onDownloadTemplate} color={Palette.Blue600} />
```
We can get it for free by just setting label.
=> feat: Put IconButton.label in a tooltip.
